/**
 * `noa.action-digest/0.1` — the committed conformance corpus, plus the properties the corpus alone
 * cannot state.
 *
 * THE CORPUS (conformance/action-digest/vectors.json) is generated by
 * `scripts/gen-action-digest-vectors.ts` from REAL seeded Ed25519 keys, so every rejection vector is
 * a cryptographically well-formed document that fails a SEMANTIC rule — never a broken blob. Each
 * vector pins its refusal REASON, not just `ok:false`: a negative that passes because some earlier
 * check happened to fire is a negative that measures nothing, and the reason string is what
 * distinguishes the two.
 *
 * THE EXTRA PROPERTIES here are the ones a fixture cannot express:
 *   - CROSS-PACKAGE PARITY. `executionGrantHash` restates the F1 rule-b convention that lives in
 *     `packages/approval-artifacts/src/refhash.ts`. A restatement without a gate is drift waiting to
 *     happen, so the rule is measured against that package's OWN committed vector — the
 *     `grantHash` inside `conformance/execution-consumption/valid.json`, produced by its `refHash`.
 *   - SCHEMA PARITY. The grant key list this module enforces is measured against the shipped
 *     `noa-execution-grant-0.1.schema.json` `required` list, so a schema change breaks this test
 *     rather than silently splitting two definitions of a valid grant.
 *   - PROJECTION KNOCKOUT. Every field of the frozen projection is removed, one at a time, and the
 *     digest must change. A field that can be deleted without moving the digest is not in the
 *     construction at all.
 *   - DETERMINISM. The same inputs digest identically across calls and across key orderings.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ACTION_DIGEST_DOMAIN,
  ACTION_DIGEST_SPEC,
  buildActionDigest,
  verifyActionDigest,
} from "../src/action-digest.js";
import { canonicalize } from "../src/jcs.js";
import { sha256Prefixed } from "../src/hash.js";
import { signingMessage } from "../src/signing.js";
import { receiptHashInput } from "../src/canonicalize.js";
import { buildReceipt } from "../src/builder.js";
import { generateKeyPair, verifyEd25519 } from "../src/keys.js";
import { verifyChain } from "../src/verify.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

interface Vector {
  name: string;
  note: string;
  /** JSON claim document; mutually exclusive with `claimText`. */
  claim?: unknown;
  /** Literal bytes for the claim (used by the malformed-input vectors). */
  claimText?: string;
  context?: unknown;
  contextText?: string;
  expect: { ok: boolean; reasonContains?: string; digest?: string };
}

interface Corpus {
  spec: string;
  domain: string;
  generatedFrom: string;
  vectors: Vector[];
}

const corpus = JSON.parse(
  readFileSync(join(ROOT, "conformance", "action-digest", "vectors.json"), "utf8"),
) as Corpus;

const bytesOf = (vec: Vector, which: "claim" | "context"): string => {
  const literal = which === "claim" ? vec.claimText : vec.contextText;
  if (typeof literal === "string") return literal;
  return JSON.stringify(which === "claim" ? vec.claim : vec.context);
};

test("the corpus is the shape the runner expects and is non-trivial", () => {
  assert.equal(corpus.spec, ACTION_DIGEST_SPEC);
  assert.equal(corpus.domain, ACTION_DIGEST_DOMAIN);
  const accepts = corpus.vectors.filter((v) => v.expect.ok).length;
  const rejects = corpus.vectors.length - accepts;
  assert.ok(accepts >= 1, `expected ≥1 ACCEPT vector, found ${accepts}`);
  assert.ok(rejects >= 12, `expected ≥12 REJECT vectors, found ${rejects}`);
  // Every rejection must pin its reason. Without this, a vector can pass by tripping the wrong rule.
  for (const v of corpus.vectors) {
    if (!v.expect.ok) {
      assert.equal(typeof v.expect.reasonContains, "string", `${v.name}: rejection vector must pin a reason`);
      assert.ok((v.expect.reasonContains as string).length > 0, `${v.name}: empty reason`);
    }
  }
});

for (const vec of corpus.vectors) {
  test(`action-digest/${vec.name} → ${vec.expect.ok ? "ACCEPT" : "REJECT"}`, () => {
    const res = verifyActionDigest(bytesOf(vec, "claim"), bytesOf(vec, "context"));
    assert.equal(res.ok, vec.expect.ok, res.ok ? "expected a refusal" : `unexpected refusal: ${res.reason}`);
    if (!res.ok) {
      assert.ok(
        res.reason.includes(vec.expect.reasonContains as string),
        `${vec.name}: refused for the WRONG reason.\n  got:      ${res.reason}\n  expected: contains "${vec.expect.reasonContains}"`,
      );
    } else if (vec.expect.digest) {
      assert.equal(res.digest, vec.expect.digest);
    }
  });
}

/** The valid vector's two source documents, reused by the property tests below. */
function validContext(): {
  chain: unknown[];
  grant: unknown;
  keyring: unknown;
  expect: { tenant: string; chain: string };
} {
  const valid = corpus.vectors.find((v) => v.expect.ok);
  assert.ok(valid, "corpus must contain an ACCEPT vector");
  return valid.context as {
    chain: unknown[];
    grant: unknown;
    keyring: unknown;
    expect: { tenant: string; chain: string };
  };
}

/** The authorization receipt inside the valid vector's chain. */
const authorizationOf = (ctx: { chain: unknown[] }): unknown => ctx.chain[0];

test("cross-package parity: executionGrantHash is the SAME F1 rule-b hash noa-approval-artifacts computes", () => {
  // GROUND TRUTH, not a restatement: this file is produced by that package's own generator, and its
  // `grantHash` is `refHash(grant)` over the grant embedded in the same fixture.
  const consumption = JSON.parse(
    readFileSync(
      join(ROOT, "packages", "approval-artifacts", "conformance", "execution-consumption", "valid.json"),
      "utf8",
    ),
  ) as {
    artifact: { grantHash: string };
    context: { refHashChecks: Array<{ path: string; rule: string; artifact: unknown }> };
  };
  const check = consumption.context.refHashChecks.find((c) => c.path === "grantHash");
  assert.ok(check, "the sibling fixture must bind grantHash");
  assert.equal(check.rule, "side", "grantHash must be an F1 rule-b (side-artifact) reference");
  assert.equal(
    sha256Prefixed(canonicalize(check.artifact)),
    consumption.artifact.grantHash,
    "this module's grant-hash rule has drifted from noa-approval-artifacts' refHash",
  );
});

test("schema parity: the enforced grant key list equals the shipped grant schema's required list", () => {
  const schema = JSON.parse(
    readFileSync(
      join(ROOT, "packages", "approval-artifacts", "schema", "noa-execution-grant-0.1.schema.json"),
      "utf8",
    ),
  ) as { required: string[]; additionalProperties: boolean };
  assert.equal(schema.additionalProperties, false, "the grant schema must stay closed");
  // A grant that satisfies the shipped schema must satisfy this module, and vice-versa. The list is
  // asserted through the module's OWN behaviour: removing any required key must refuse.
  const ctx = validContext();
  for (const key of schema.required) {
    const grant = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;
    delete grant[key];
    const res = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(grant));
    assert.equal(res.ok, false, `a grant missing required key "${key}" was accepted`);
  }
  // And an EXTRA key is refused too (additionalProperties:false parity).
  const extra = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;
  extra["surprise"] = 1;
  assert.equal(buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(extra)).ok, false);

  // ── THE NESTED OBJECT, WHICH THIS TEST USED TO MISS ENTIRELY (round-2 QA) ────────────────────
  // Walking only `schema.required` measured the top level and nothing else, so `sig.extra` sailed
  // through here while verifyArtifact refused it. The schema's `$defs.sig` is closed and carries its
  // own required list; both halves are now derived from the shipped file rather than restated.
  const sigDef = (schema as unknown as { $defs: { sig: { required: string[]; additionalProperties: boolean } } }).$defs.sig;
  assert.equal(sigDef.additionalProperties, false, "the grant schema's sig object must stay closed");
  for (const key of sigDef.required) {
    const grant = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;
    delete (grant["sig"] as Record<string, unknown>)[key];
    assert.equal(
      buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(grant)).ok,
      false,
      `a grant whose sig is missing required key "${key}" was accepted`,
    );
  }
  const sigExtra = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;
  (sigExtra["sig"] as Record<string, unknown>)["extra"] = "x";
  const sigExtraResult = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(sigExtra));
  assert.equal(sigExtraResult.ok, false, "grant.sig.extra was accepted");
  assert.match(sigExtraResult.ok ? "" : sigExtraResult.reason, /grant\.sig: unknown property/);
});

/**
 * WHAT THIS TEST PROVES, AND — CORRECTED IN ROUND 2 — WHAT IT DOES NOT.
 *
 * It proves each member is IN the hashed bytes: delete one and the digest moves. That is all. It was
 * previously cited as evidence that each member is independently load-bearing against an attack, and
 * that citation was FALSE. Pinning `tenant`, `chain`, `actionId`, `actionCanonical`,
 * `executionGrantId` or `executionNonce` to a constant leaves every corresponding attack vector
 * REJECTED, because `authorizationReceiptHash` and `executionGrantHash` — hashes over the whole
 * receipt and the whole grant — already refuse them. `test/action-digest.test.ts` cannot isolate
 * those six by construction: any source mutation that moves one of them necessarily moves a
 * whole-document hash as well.
 *
 * `tenant` and `chain` are the exception, and not because of the digest: they additionally drive the
 * expected-scope comparison in `verifyActionDigest`, which is a genuinely independent rejection path
 * with its own isolating vectors (`reject-cross-tenant-expectation`, `reject-cross-chain-expectation`).
 */
test("projection knockout: deleting ANY projection field changes the digest (bytes only — see above)", () => {
  const ctx = validContext();
  const built = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(ctx.grant));
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const projection = built.projection as unknown as Record<string, unknown>;
  const keys = Object.keys(projection);
  assert.equal(keys.length, 10, `the frozen projection is 10 fields; found ${keys.length}: ${keys.join(",")}`);
  const digestOf = (p: unknown): string =>
    sha256Prefixed(signingMessage(ACTION_DIGEST_DOMAIN, canonicalize(p)));
  assert.equal(digestOf(projection), built.digest, "the digest is not the domain-tagged hash of the projection");
  for (const key of keys) {
    const knocked = { ...projection };
    delete knocked[key];
    assert.notEqual(
      digestOf(knocked),
      built.digest,
      `projection field "${key}" can be deleted without moving the digest — it is not in the construction`,
    );
  }
});

/**
 * FIELD DIFFERENTIAL — does each projection slot separate two authorizations that differ ONLY there?
 *
 * This is the honest version of "every field earns its place", and it is worth stating what it does
 * and does not show. `authorizationReceiptHash` and `executionGrantHash` are hashes over WHOLE
 * documents, so between them they already commit to every other slot; the last two rows below prove
 * that by moving a receipt field and a grant field that appear in NO other slot. The middle rows are
 * therefore REDUNDANT BY CONSTRUCTION — they are in the projection because `carlos.md` §3's frozen
 * list prescribes them, and what they buy is that the projection is self-describing: an independent
 * implementer who maps `action.canonical` into the `actionId` slot gets a different digest instead
 * of a lucky agreement. Redundancy stated, not hidden.
 *
 * NOTE THE LIMIT OF THIS TEST, corrected in round 2: it shows the digest SEPARATES authorizations
 * that differ in each slot. It does NOT show the named slot is what separates them — the two
 * whole-document hashes move too, and would refuse these pairs on their own.
 */
test("field differential: each projection slot separates authorizations that differ only there", () => {
  const ctx = validContext();
  const baseDigest = (() => {
    const b = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(ctx.grant));
    assert.ok(b.ok, b.ok ? "" : b.reason);
    return b.digest;
  })();

  type Doc = Record<string, unknown>;
  const clone = (v: unknown): Doc => JSON.parse(JSON.stringify(v)) as Doc;

  /**
   * Apply a receipt mutation and RE-ANCHOR: recompute the receipt's own chain.hash and re-point the
   * grant at it. Signatures are left as-is on purpose — this module verifies none, so re-signing
   * would test the signer rather than the construction.
   */
  function mutated(mutate: (r: Doc, g: Doc) => void): string {
    const receipt = clone(authorizationOf(ctx));
    const grant = clone(ctx.grant);
    mutate(receipt, grant);
    const rehash = sha256Prefixed(receiptHashInput(receipt as never));
    (receipt["chain"] as Doc)["hash"] = rehash;
    if (grant["approvalReceiptHash"] === (clone(ctx.grant) as Doc)["approvalReceiptHash"]) {
      grant["approvalReceiptHash"] = rehash;
    }
    const built = buildActionDigest(JSON.stringify(receipt), JSON.stringify(grant));
    assert.ok(built.ok, built.ok ? "" : `mutation produced an unbuildable pair: ${built.reason}`);
    return built.digest;
  }

  const cases: Array<[string, (r: Doc, g: Doc) => void]> = [
    ["tenant", (r) => { (r["scope"] as Doc)["tenant"] = "tenant-globex"; }],
    ["chain", (r) => { (r["scope"] as Doc)["chain"] = "chain-other-9"; }],
    ["actionId", (r) => { (r["action"] as Doc)["id"] = "deploy.rollback"; }],
    ["actionCanonical", (r) => { (r["action"] as Doc)["canonical"] = "deploy.apply:prod/db"; }],
    ["actionParamsHash", (r, g) => {
      const other = "sha256:" + "dd".repeat(32);
      (r["action"] as Doc)["paramsHash"] = other;
      g["paramsHash"] = other; // the grant authorizes ONE param hash; moving one without the other is refused
    }],
    ["executionGrantId", (_r, g) => { g["grantId"] = "grant-999"; }],
    ["executionNonce", (_r, g) => { g["nonce"] = "b9".repeat(32); }], // hex64 — the nonce rule applies to mutants too
    // THE TWO LOAD-BEARING ROWS. Each moves a field that lives in no other projection slot, so only
    // the whole-document hash can carry it.
    ["executionGrantHash (via a grant field in no other slot)", (_r, g) => {
      g["holdEnvelopeHash"] = "sha256:" + "ee".repeat(32);
    }],
    ["authorizationReceiptHash (via a receipt field in no other slot)", (r) => {
      (r["agent"] as Doc)["id"] = "approver-z";
    }],
  ];

  for (const [label, mutate] of cases) {
    assert.notEqual(mutated(mutate), baseDigest, `${label}: the digest did not move — this slot separates nothing`);
  }
});

test("domain separation: the SAME projection under any other tag is a different value", () => {
  const ctx = validContext();
  const built = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(ctx.grant));
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const jcs = canonicalize(built.projection);
  const others = ["NOA-Receipt-v0.1-sig", "NOA-Checkpoint-v0.1-sig", "NOA-ExecGrant-v0.1-sig", "NOA-ActionDigest-v0.1-sig"];
  for (const tag of others) {
    assert.notEqual(sha256Prefixed(signingMessage(tag, jcs)), built.digest, `tag ${tag} collided`);
  }
  // And the untagged hash — what an implementation that forgot domain separation would emit.
  assert.notEqual(sha256Prefixed(jcs), built.digest, "the untagged hash equals the digest: the tag is not applied");
});

test("determinism: the digest does not depend on JSON key order or on repeated calls", () => {
  const ctx = validContext();
  const a = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(ctx.grant));
  const b = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(ctx.grant));
  assert.ok(a.ok && b.ok);
  assert.equal(a.digest, b.digest);
  // Re-serialize the grant with reversed key order: JCS must absorb it.
  const grant = ctx.grant as Record<string, unknown>;
  const reversed: Record<string, unknown> = {};
  for (const k of Object.keys(grant).reverse()) reversed[k] = grant[k];
  const c = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(reversed));
  assert.ok(c.ok, c.ok ? "" : c.reason);
  assert.equal(c.digest, a.digest, "key order changed the digest — the construction is not canonical");
});

test("the builder and the verifier agree: the built digest is the one the verifier accepts", () => {
  const ctx = validContext();
  const built = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(ctx.grant));
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const res = verifyActionDigest(
    JSON.stringify({ spec: ACTION_DIGEST_SPEC, digest: built.digest }),
    JSON.stringify(ctx),
  );
  assert.equal(res.ok, true, res.ok ? "" : res.reason);
});

/**
 * THE FORGERY THAT USED TO BE ACCEPTED — now the regression test for HIGH-3.
 *
 * The previous revision of this file asserted that a fully forged pair was ACCEPTED, and defended
 * that with a prose precondition in `docs/action-digest-spec.md` §6. Round-2 QA refused the defence
 * and was right: a classification string does not enforce call ordering and does not stop document
 * substitution, on a surface authorization decisions rest on. `verifyActionDigest` now authenticates
 * its own inputs, so the same bytes are REFUSED — and refused for the authenticity reason, not by
 * accident on some later check.
 */
test("HIGH-3: a forged authorization is REFUSED, and refused for the authenticity reason", () => {
  const ctx = validContext();
  const evil = generateKeyPair("gate-prod-1"); // attacker key claiming the gate's kid
  const forged = buildReceipt(
    {
      id: "rcpt_forged",
      ts: "2026-07-14T11:55:00.000Z",
      scope: { tenant: "tenant-acme", chain: "chain-acme-1" },
      agent: { id: "approver-a", model: null, principal: "HUMAN" },
      action: {
        id: "wire.transfer",
        canonical: "wire.transfer:attacker-acct",
        riskClass: "HIGH",
        paramsHash: "sha256:" + "99".repeat(32),
        reversible: false,
        rollbackRef: null,
      },
      governance: {
        mode: "on",
        verdict: "ALLOWED",
        ruleId: "human-approved",
        approval: { by: "HUMAN:cfo@victim.example", at: "2026-07-14T11:55:00.000Z" },
        sandboxed: false,
      },
    },
    null,
    { kid: evil.kid, privateKey: evil.privateKey },
  );
  const grant = {
    spec: "noa.execution-grant/0.1",
    grantId: "grant-forged",
    holdId: "hold-forged",
    paramsHash: forged.action.paramsHash,
    holdEnvelopeHash: "sha256:" + "00".repeat(32),
    approvalReceiptHash: sha256Prefixed(receiptHashInput(forged)),
    issuedAt: "2026-07-14T11:55:00.000Z",
    expiresAt: "2026-07-14T12:30:00.000Z",
    maxUses: 1,
    nonce: "f0".repeat(32), // hex64 — the forgery lives in the KEY, not the nonce shape
    sig: { alg: "ed25519", kid: "gate-prod-1", value: Buffer.alloc(64).toString("base64") },
  };

  // The BUILDER is the producer-side construction and still constructs — it takes no trust root and
  // returns no verdict. That split is the contract, and it is asserted rather than assumed.
  const built = buildActionDigest(JSON.stringify(forged), JSON.stringify(grant));
  assert.ok(built.ok, built.ok ? "" : built.reason);

  const res = verifyActionDigest(
    JSON.stringify({ spec: ACTION_DIGEST_SPEC, digest: built.digest }),
    JSON.stringify({ chain: [forged], grant, keyring: ctx.keyring, expect: ctx.expect }),
  );
  assert.equal(res.ok, false, "a forged authorization was accepted");
  assert.match(
    res.ok ? "" : res.reason,
    /not authentic/,
    "refused, but not for the authenticity reason — the control under test never ran",
  );
});

test("HIGH-3: the verifier refuses when it cannot authenticate at all", () => {
  const ctx = validContext();
  const built = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(ctx.grant));
  assert.ok(built.ok);
  const claim = JSON.stringify({ spec: ACTION_DIGEST_SPEC, digest: built.digest });
  // No keyring at all.
  const noRoot = verifyActionDigest(claim, JSON.stringify({ chain: ctx.chain, grant: ctx.grant, expect: ctx.expect }));
  assert.equal(noRoot.ok, false);
  assert.match(noRoot.ok ? "" : noRoot.reason, /context\.keyring/);
  // An empty keyring is not a permissive one.
  const emptyRoot = verifyActionDigest(
    claim,
    JSON.stringify({ chain: ctx.chain, grant: ctx.grant, keyring: {}, expect: ctx.expect }),
  );
  assert.equal(emptyRoot.ok, false);
});

/**
 * GRANT-SIGNATURE PARITY — the one rule this module restates, measured against ground truth.
 *
 * `GRANT_SIG_DOMAIN` and the `<domain> ++ SHA256(JCS(doc without sig))` preimage belong to
 * `packages/approval-artifacts`, which this package has no dependency edge to. So the restatement is
 * checked against THAT package's own committed conformance vectors: its real gate-signed grant must
 * verify under this module's rule with its own keyring's public key, and its committed
 * tampered/wrong-key grants must not. If either package's rule moves, this test fails.
 */
test("cross-package parity: the grant signature rule matches noa-approval-artifacts' own vectors", () => {
  const aaDir = join(ROOT, "packages", "approval-artifacts", "conformance");
  const keyring = JSON.parse(readFileSync(join(aaDir, "keyring.json"), "utf8")) as Record<string, { publicKey: string }>;
  const load = (f: string): { artifact: Record<string, unknown> } =>
    JSON.parse(readFileSync(join(aaDir, "execution-grant", f), "utf8")) as { artifact: Record<string, unknown> };

  const check = (grant: Record<string, unknown>): boolean => {
    const sig = grant.sig as { kid: string; value: string };
    const pub = keyring[sig.kid]?.publicKey;
    if (!pub) return false;
    const withoutSig: Record<string, unknown> = { ...grant };
    delete withoutSig.sig;
    return verifyEd25519(pub, signingMessage("NOA-ExecGrant-v0.1-sig", canonicalize(withoutSig)), sig.value);
  };

  assert.equal(check(load("valid.json").artifact), true, "the sibling package's REAL signed grant did not verify under this module's rule");
  assert.equal(check(load("reject-tampered-content.json").artifact), false, "a grant altered after signing verified");

  // ── THE BOUNDARY, ASSERTED RATHER THAN DESCRIBED ────────────────────────────────────────────
  // The sibling's `reject-wrong-key` vector is an F15 ROLE rejection: `gate-holdonly-9` holds
  // `hold-signer` only, so `verifyArtifact` refuses it — while its signature is perfectly genuine.
  // This module checks signatures and does NOT evaluate the F15 role matrix, so it MUST accept that
  // signature. Pinning the true behaviour here is what stops the module's documented residual
  // (docs/action-digest-spec.md §6) from quietly becoming false in either direction.
  assert.equal(
    check(load("reject-wrong-key.json").artifact),
    true,
    "the F15 role-rejection vector's signature must still verify — this module does not evaluate roles, and the residual says so",
  );
});

/**
 * BUILDER-LEVEL CONTROLS THAT AUTHENTICATION NOW SHADOWS AT THE VERIFIER.
 *
 * Adding chain authentication made three refusals unreachable through `verifyActionDigest`: a
 * tampered receipt is refused as inauthentic before its self-hash is recomputed, and a grant that
 * references another authorization is refused by chain SELECTION before the builder's own tie check
 * runs. Those are strictly stronger refusals — but the underlying controls still exist, and a
 * control nothing exercises is a control nobody will notice breaking. They are measured here at the
 * layer where they remain reachable.
 */
test("builder controls stay measured where the verifier now shadows them", () => {
  const ctx = validContext();
  const receipt = JSON.parse(JSON.stringify(authorizationOf(ctx))) as Record<string, unknown>;
  const grant = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;

  // (a) receipt edited after hashing — the committed chain.hash no longer describes the body.
  const edited = JSON.parse(JSON.stringify(receipt)) as Record<string, unknown>;
  (edited["action"] as Record<string, unknown>)["riskClass"] = "LOW";
  const editedResult = buildActionDigest(JSON.stringify(edited), JSON.stringify(grant));
  assert.equal(editedResult.ok, false);
  assert.match(editedResult.ok ? "" : editedResult.reason, /receipt\.chain\.hash/);

  // (b) a grant bound to a different authorization.
  const foreign = JSON.parse(JSON.stringify(grant)) as Record<string, unknown>;
  foreign["approvalReceiptHash"] = "sha256:" + "11".repeat(32);
  const foreignResult = buildActionDigest(JSON.stringify(receipt), JSON.stringify(foreign));
  assert.equal(foreignResult.ok, false);
  assert.match(foreignResult.ok ? "" : foreignResult.reason, /does not reference this receipt/);

  // (c) a tenant-less receipt still yields no digest at the construction layer.
  const tenantless = JSON.parse(JSON.stringify(receipt)) as Record<string, unknown>;
  delete (tenantless["scope"] as Record<string, unknown>)["tenant"];
  const tenantlessResult = buildActionDigest(JSON.stringify(tenantless), JSON.stringify(grant));
  assert.equal(tenantlessResult.ok, false);
  assert.match(tenantlessResult.ok ? "" : tenantlessResult.reason, /receipt\.scope\.tenant/);
});

test("HIGH-1 at the builder: every non-ALLOWED verdict is refused", () => {
  const ctx = validContext();
  const grant = ctx.grant;
  for (const verdict of ["BLOCKED", "DEFERRED", "EXECUTED", "FAILED", "ROLLED_BACK", "SIMULATED"]) {
    const receipt = JSON.parse(JSON.stringify(authorizationOf(ctx))) as Record<string, unknown>;
    (receipt["governance"] as Record<string, unknown>)["verdict"] = verdict;
    // Re-anchor so the ONLY thing wrong is the verdict, not a stale self-hash.
    (receipt["chain"] as Record<string, unknown>)["hash"] = sha256Prefixed(receiptHashInput(receipt as never));
    const g = JSON.parse(JSON.stringify(grant)) as Record<string, unknown>;
    g["approvalReceiptHash"] = (receipt["chain"] as Record<string, unknown>)["hash"];
    const res = buildActionDigest(JSON.stringify(receipt), JSON.stringify(g));
    assert.equal(res.ok, false, `verdict ${verdict} was correlated as an authorization`);
    assert.match(res.ok ? "" : res.reason, /governance\.verdict/, `verdict ${verdict} refused for the wrong reason`);
  }
});

test("an expired grant still digests, deliberately — a correlation key must not decay", () => {
  const ctx = validContext();
  const grant = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;
  grant["expiresAt"] = "2020-01-01T00:00:00.000Z";
  const built = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(grant));
  // Expiry is the GRANT verifier's job (`verifyArtifact` + `mustBeAfter`). If the digest refused an
  // expired grant, every audit lookup would stop matching the day the grant timed out — a
  // correlation key that decays correlates nothing. It is still a DIFFERENT value, because
  // `expiresAt` is inside the grant document that `executionGrantHash` covers.
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const original = buildActionDigest(JSON.stringify(authorizationOf(ctx)), JSON.stringify(ctx.grant));
  assert.ok(original.ok);
  assert.notEqual(built.digest, original.digest);
});

test("nothing throws: hostile bytes yield a refusal, never an exception", () => {
  const hostile = [
    "",
    "null",
    "[]",
    "{",
    '{"spec":"noa.action-digest/0.1"}',
    '"sha256:' + "0".repeat(64) + '"',
    " ",
  ];
  for (const h of hostile) {
    const res = verifyActionDigest(h, h);
    assert.equal(res.ok, false, `hostile input accepted: ${JSON.stringify(h)}`);
    assert.equal(typeof res.reason, "string");
  }
});
