/**
 * `noa.deploy.release/1` — the committed conformance corpus, plus the properties the corpus alone
 * cannot state.
 *
 * THE CORPUS (conformance/deploy-release/vectors.json) is generated by
 * `scripts/gen-deploy-release-vectors.ts`, which REPLAYS every vector against the implementation
 * before writing. This suite re-runs the committed file independently, so a stale or hand-edited
 * corpus fails here even if the generator was never re-run.
 *
 * THE NORMATIVE PINS. The three hex constants below are the values `docs/deploy-release-spec.md`
 * §6-§7 declares a conforming implementation must compute. They are restated HERE as literals,
 * independently of the module's own constants and of the generator's copy, so the implementation,
 * the corpus, the generator and this suite must all agree before anything goes green. If a value
 * drifts, the response is NEVER to re-pin from whatever the local implementation now returns —
 * that would make the test agree with the regression it exists to catch.
 *
 * ⚠ WHAT THESE PINS DO NOT PROVE, because an earlier revision of this header claimed it. They are
 * NOT a private producer's attestation, and this suite cannot reach any producer. Every copy
 * compared here is public, so all of them could move together while a non-public implementation
 * differed and this file would stay green. That gap is real, is stated in the module header and in
 * `NON-CLAIMS.md` §S6, and would be closed by a signed parity manifest that does not exist. What
 * this suite DOES prove is internal agreement plus ANTI-VACUITY: the last test mutates each pin by
 * one character and requires the check that depends on it to fail, so a pin cannot decay into
 * decoration while still being printed as evidence.
 *
 * THE EXTRA PROPERTIES here are the ones a fixture file cannot express: identity distinctness,
 * Release-line injectivity over a set, single-field digest separation as a PAIRWISE property,
 * display completeness measured mechanically, determinism across calls, and the closed-enum type
 * agreeing with the runtime table it claims to describe.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  DEPLOY_RELEASE_SPEC,
  DEPLOY_RELEASE_CANONICAL,
  DEPLOY_RELEASE_IMPLEMENTATION_DIGEST,
  DEPLOY_RELEASE_SCHEMA_ID,
  DEPLOY_RELEASE_DISPLAY_ID,
  projectionIdentityHash,
  projectDeployRelease,
} from "../src/deploy-release.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

// ── THE NORMATIVE PINS, restated independently of the module and of the generator ────────────────
const PIN_SCHEMA_HASH = "sha256:181779a415d998bb89e3c07cd42fd247fb272303bbb164faa953a1bcf03d0b70";
const PIN_DISPLAY_HASH = "sha256:75fdd2b6f5674b8a4c274fb08ba7329870501dbb76b9d4646b929a9643b33d3b";
const PIN_PARAMS_HASH = "sha256:97fff28779b378933054a67648b3e4c22dc9f774c7374d6f32f2fec990c58f7a";

// ── THE FIXTURE, SYNTHETIC BY CONSTRUCTION, AND NAMED EXACTLY ONCE ───────────────────────────────
// Every identifier is unmistakably fake BY CONSTRUCTION rather than by assertion: RFC 2606 reserves
// `.invalid`, so the repository can never resolve; the accounts come from the reserved synthetic
// namespace `acct-example-N` (a numbered account publishes the shape of a real deployment); the
// digests are counting patterns no content-addressed artifact produces. That matters more here than
// in an ordinary suite, because this fixture is the PREIMAGE of the published `paramsHash` — it is
// readable straight out of the public corpus, so it must name no real system.
//
// They are CONSTANTS, and every use below derives from them — INCLUDING the raw-JSON literals, which
// is the point. An earlier revision hand-wrote the tuple inline in the duplicate-key vector; that
// second copy was missed when the fixture was sanitised and survived as the one place still naming a
// real repository. A fixture spelled twice is a fixture that cannot be sanitised once.
const REPOSITORY = "example.invalid/example-service";
const TARGET_ACCOUNT = "acct-example-1";
const TARGET_ACCOUNT_B = "acct-example-2";
const COMMIT_A = "0123456789abcdef0123456789abcdef01234567";
const COMMIT_B = "0123456789abcdef0123456789abcdef01234568";
const DIGEST_A = "sha256:00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff";

function baseParams(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    repository: REPOSITORY,
    commit: COMMIT_A,
    environment: "staging",
    imageDigest: DIGEST_A,
    targetAccount: TARGET_ACCOUNT,
    operation: "deploy",
    ...overrides,
  };
}

const run = (params: unknown): ReturnType<typeof projectDeployRelease> =>
  projectDeployRelease(JSON.stringify(params));

interface IdentityVector {
  name: string;
  note: string;
  descriptor: { id: string; version: number; kind: "actionSchema" | "displayProjection"; implementation: string };
  expect: { hash: string };
}
interface ParamsVector {
  name: string;
  note: string;
  params?: unknown;
  paramsText?: string;
  expect: { ok: boolean; paramsHash?: string; display?: Record<string, string>; reasonContains?: string };
}
interface Corpus {
  spec: string;
  canonical: string;
  implementationDigest: string;
  generatedFrom: string;
  vectors: Array<IdentityVector | ParamsVector>;
}

const corpus = JSON.parse(
  readFileSync(join(ROOT, "conformance", "deploy-release", "vectors.json"), "utf8"),
) as Corpus;

const isIdentity = (v: IdentityVector | ParamsVector): v is IdentityVector =>
  (v as IdentityVector).descriptor !== undefined;

test("the corpus is the shape the runner expects and is non-trivial", () => {
  assert.equal(corpus.spec, DEPLOY_RELEASE_SPEC);
  assert.equal(corpus.canonical, DEPLOY_RELEASE_CANONICAL);
  assert.equal(corpus.implementationDigest, DEPLOY_RELEASE_IMPLEMENTATION_DIGEST);
  const identities = corpus.vectors.filter(isIdentity);
  const params = corpus.vectors.filter((v) => !isIdentity(v)) as ParamsVector[];
  const accepts = params.filter((v) => v.expect.ok).length;
  const rejects = params.length - accepts;
  assert.equal(identities.length, 2, "both projection identities must be pinned as vectors");
  assert.ok(accepts >= 10, `expected ≥10 ACCEPT vectors, found ${accepts}`);
  assert.ok(rejects >= 55, `expected ≥55 REJECT vectors, found ${rejects}`);
  for (const v of params) {
    if (v.expect.ok) {
      assert.equal(typeof v.expect.paramsHash, "string", `${v.name}: accept vector must pin its paramsHash`);
    } else {
      // Every rejection pins its reason. Without this, a vector can pass by tripping the wrong rule.
      assert.equal(typeof v.expect.reasonContains, "string", `${v.name}: rejection vector must pin a reason`);
      assert.ok((v.expect.reasonContains as string).length > 0, `${v.name}: empty reason`);
    }
  }
});

for (const vec of corpus.vectors) {
  if (isIdentity(vec)) {
    test(`deploy-release/${vec.name} → identity recomputes from its descriptor`, () => {
      assert.equal(projectionIdentityHash(vec.descriptor), vec.expect.hash);
    });
    continue;
  }
  test(`deploy-release/${vec.name} → ${vec.expect.ok ? "ACCEPT" : "REJECT"}`, () => {
    const bytes = typeof vec.paramsText === "string" ? vec.paramsText : JSON.stringify(vec.params);
    const res = projectDeployRelease(bytes);
    assert.equal(res.ok, vec.expect.ok, res.ok ? "expected a refusal" : `unexpected refusal: ${res.reason}`);
    if (!res.ok) {
      assert.ok(
        res.reason.includes(vec.expect.reasonContains as string),
        `${vec.name}: refused for the WRONG reason.\n  got:      ${res.reason}\n  expected: contains "${vec.expect.reasonContains}"`,
      );
    } else {
      assert.equal(res.paramsHash, vec.expect.paramsHash);
      if (vec.expect.display) assert.deepEqual({ ...res.display }, vec.expect.display);
    }
  });
}

// ── THE THREE NORMATIVE PINS, ASSERTED AGAINST THE MODULE DIRECTLY ───────────────────────────────
// The corpus pins them too, but the corpus is a generated file: these literals are the independent
// copy that a regenerated-and-recommitted corpus cannot silently move.

test("the schema identity recomputes byte-identically to its published value", () => {
  assert.equal(DEPLOY_RELEASE_SCHEMA_ID.id, "noa.deploy.release.schema");
  assert.equal(DEPLOY_RELEASE_SCHEMA_ID.version, 1);
  assert.equal(DEPLOY_RELEASE_SCHEMA_ID.hash, PIN_SCHEMA_HASH);
  // And not as a stored constant: from the construction plus the pinned implementation digest.
  assert.equal(
    projectionIdentityHash({
      id: "noa.deploy.release.schema",
      version: 1,
      kind: "actionSchema",
      implementation: DEPLOY_RELEASE_IMPLEMENTATION_DIGEST,
    }),
    PIN_SCHEMA_HASH,
  );
});

test("the display identity recomputes byte-identically to its published value", () => {
  assert.equal(DEPLOY_RELEASE_DISPLAY_ID.id, "noa.deploy.release.display");
  assert.equal(DEPLOY_RELEASE_DISPLAY_ID.version, 1);
  assert.equal(DEPLOY_RELEASE_DISPLAY_ID.hash, PIN_DISPLAY_HASH);
  // The two identities MUST differ: same artifact, different kind. If a refactor ever made them
  // equal, one of the two roles would be unpinned and nothing else here would notice.
  assert.notEqual(DEPLOY_RELEASE_DISPLAY_ID.hash, DEPLOY_RELEASE_SCHEMA_ID.hash);
});

test("the conformance tuple binds the published paramsHash, deterministically", () => {
  const r1 = run(baseParams());
  const r2 = run(baseParams());
  assert.ok(r1.ok && r2.ok);
  assert.equal(r1.paramsHash, PIN_PARAMS_HASH);
  assert.equal(r1.paramsHash, r2.paramsHash);
  assert.deepEqual(r1.display, r2.display);
  assert.equal(r1.actionSchema.hash, PIN_SCHEMA_HASH);
  assert.equal(r1.displayProjection.hash, PIN_DISPLAY_HASH);
  // max 4–5 display rows — and every BOUND field is visible inside them (measured below).
  assert.ok(Object.keys(r1.display).length <= 5);
});

test("every bound value is visible to the approver (a hash is not verified context)", () => {
  const r = run(baseParams());
  assert.ok(r.ok);
  assert.deepEqual(
    { ...r.display },
    {
      Action: "noa.deploy.release",
      Release: `deploy example.invalid/example-service@${COMMIT_A}`,
      Environment: "staging",
      Target: TARGET_ACCOUNT,
      Image: DIGEST_A,
    },
  );
  // Mechanical completeness: every bound VALUE appears verbatim in what is rendered. The
  // hand-written expectation above stops being a completeness check the moment a seventh param is
  // added and nobody updates it; this arm fails in that case.
  const rendered = Object.values(r.display).join("\u0000");
  const a = baseParams();
  for (const k of Object.keys(a)) {
    assert.ok(rendered.includes(String(a[k])), `bound param \`${k}\` is not visible to the approver`);
  }
});

test("no two deployments render the same Release line (injectivity, parsed from the right)", () => {
  // Chosen to collide for a LEFT-to-right parser: repositories that end in `@` + 40 hex. The line
  // is injective only because `commit` is fixed-width and the charset admits no whitespace.
  const other = "b".repeat(39) + "1";
  const tuples: Record<string, unknown>[] = [
    {},
    { commit: other },
    { operation: "rollback" },
    { repository: "example.invalid/other-service" },
    { repository: `example.invalid/svc@${COMMIT_A}` },
    { repository: `example.invalid/svc@${COMMIT_A}`, commit: other },
    { repository: `example.invalid/svc@${other}`, commit: COMMIT_A },
    { repository: "example.invalid/svc@sub", commit: other },
  ];
  const lines = new Set<string>();
  const hashes = new Set<string>();
  for (const t of tuples) {
    const r = run(baseParams(t));
    assert.ok(r.ok, `expected a valid deployment: ${JSON.stringify(r)}`);
    lines.add(String(r.display["Release"]));
    hashes.add(r.paramsHash);
  }
  assert.equal(hashes.size, tuples.length, "each tuple is a genuinely different deployment");
  assert.equal(
    lines.size,
    tuples.length,
    "two different deployments rendered the SAME line to the approver — the human would be " +
      "authorizing one of two things and could not tell which",
  );
});

test("every single-field change moves the digest (exact authority permits only the exact attempt)", () => {
  const base = run(baseParams());
  assert.ok(base.ok);
  const moved = (o: Record<string, unknown>): string => {
    const r = run(baseParams(o));
    assert.ok(r.ok, `expected an accepted tuple: ${JSON.stringify(r)}`);
    return r.paramsHash;
  };
  // Each attacked tuple is itself VALID — an enforcing gate refuses it because it is DIFFERENT,
  // not because it is malformed. Refusing every mutation outright would be a different (and
  // weaker) property than exact binding.
  const hashes = [
    base.paramsHash,
    moved({ commit: COMMIT_B }),
    moved({ environment: "production" }),
    moved({ imageDigest: DIGEST_A.slice(0, -1) + "2" }),
    moved({ repository: "example.invalid/other-service" }),
    moved({ targetAccount: TARGET_ACCOUNT_B }),
    moved({ operation: "rollback" }),
  ];
  assert.equal(new Set(hashes).size, hashes.length, "each bound field must independently move the digest");
});

test("the caller's key order is irrelevant: JCS makes the digest a property of the deployment", () => {
  const a = baseParams();
  const reordered: Record<string, unknown> = {
    operation: a["operation"],
    targetAccount: a["targetAccount"],
    imageDigest: a["imageDigest"],
    environment: a["environment"],
    commit: a["commit"],
    repository: a["repository"],
  };
  const r1 = run(a);
  const r2 = run(reordered);
  assert.ok(r1.ok && r2.ok);
  assert.equal(r2.paramsHash, r1.paramsHash);
});

test("the accepted key set is EXACTLY the six (adding any own key flips a valid tuple to refusal)", () => {
  const clean = run(baseParams());
  assert.ok(clean.ok, "pair-discipline control: the clean tuple is accepted");
  assert.equal(clean.paramsHash, PIN_PARAMS_HASH);
  for (const junk of ["force", "deploymentCommand", "x", "__proto__x", "argv", "cwd", "executable", "targetEnv", "Operation", " operation", "operation2"]) {
    const r = run({ ...baseParams(), [junk]: "anything" });
    assert.equal(r.ok, false, `an extra key must be refused — \`${junk}\` is not a deploy field`);
    assert.ok(!r.ok && r.reason.includes("unrecognized field"), `\`${junk}\`: wrong refusal reason`);
  }
});

test("the label bound is 256, measured on both sides", () => {
  assert.equal(run(baseParams({ repository: "a".repeat(256) })).ok, true, "256 is the bound, not 255");
  assert.equal(run(baseParams({ repository: "a".repeat(257) })).ok, false, "257 is past the bound");
});

test("the byte boundary refuses what an object API could never even see", () => {
  // Duplicate keys: JSON.parse would keep the last one silently; the strict parser refuses.
  const dup =
    `{"repository":"${REPOSITORY}","commit":"${COMMIT_B}","commit":"${COMMIT_A}",` +
    `"environment":"staging","imageDigest":"${DIGEST_A}","targetAccount":"${TARGET_ACCOUNT}","operation":"deploy"}`;
  const r1 = projectDeployRelease(dup);
  assert.ok(!r1.ok && r1.reason.includes("duplicate object key"));
  // `__proto__` as an own key is refused at the parse boundary.
  const proto = `{"__proto__":{},"repository":"x","commit":"${COMMIT_A}","environment":"staging","imageDigest":"${DIGEST_A}","targetAccount":"a","operation":"deploy"}`;
  const r2 = projectDeployRelease(proto);
  assert.ok(!r2.ok && r2.reason.includes("forbidden object key"));
  // A caller-owned OBJECT is not a document: refused without traversal (ADR §3.1; the C2 probe in
  // test/security/entry-point-coverage.test.ts measures the zero-read property mechanically).
  const r3 = projectDeployRelease(baseParams() as unknown as string);
  assert.equal(r3.ok, false);
});

test("the exported identities are inert: a consumer cannot repoint what an envelope is compared to", () => {
  assert.ok(Object.isFrozen(DEPLOY_RELEASE_SCHEMA_ID));
  assert.ok(Object.isFrozen(DEPLOY_RELEASE_DISPLAY_ID));
  assert.equal(Object.getPrototypeOf(DEPLOY_RELEASE_SCHEMA_ID), null, "null-rooted: no chain to poison");
  assert.throws(() => {
    (DEPLOY_RELEASE_SCHEMA_ID as { hash: string }).hash = "sha256:" + "0".repeat(64);
  }, TypeError);
});

/**
 * THE PUBLISHED TYPE MUST AGREE WITH THE RUNTIME TABLE IT CLAIMS TO DESCRIBE.
 *
 * `DeployOperation` is a closed union and `DEPLOY_OPERATIONS` is a closed runtime table; they are
 * two statements of one rule, and two statements of one rule are how the rule becomes two. The
 * published type was `string` in an earlier revision — which told every consumer that a third
 * operation is representable while the validator refused it — so this pins them against each other
 * from the OUTSIDE, through the public entry point, in both directions.
 */
test("the closed operation enum: exactly {deploy, rollback} accept, and nothing else does", () => {
  const MEMBERS: readonly string[] = ["deploy", "rollback"];
  for (const op of MEMBERS) {
    const r = run(baseParams({ operation: op }));
    assert.equal(r.ok, true, `\`${op}\` is a member of the union and must be accepted`);
  }
  // Everything a caller might reach for, including the prototype-flavoured strings a membership
  // test written with `in` or a plain object literal would have waved through.
  for (const op of ["restart", "DEPLOY", "Deploy", "deploy ", " deploy", "", "redeploy", "rollback2",
                    "__proto__", "constructor", "toString", "valueOf", "hasOwnProperty"]) {
    const r = run(baseParams({ operation: op }));
    assert.equal(r.ok, false, `\`${op}\` is not a member of the union and must be refused`);
  }
  // The accepted set is EXACTLY the union, measured rather than asserted: any accepted operation
  // must be one the type admits.
  const accepted = ["deploy", "rollback", "restart", "DEPLOY", "redeploy", "__proto__"]
    .filter((op) => run(baseParams({ operation: op })).ok);
  assert.deepEqual(accepted, [...MEMBERS], "the runtime table and the published union must not diverge");
});

/**
 * ANTI-VACUITY: EVERY PIN IS LOAD-BEARING.
 *
 * ── WHY THIS TEST EXISTS ─────────────────────────────────────────────────────────────────────────
 *
 * An independent review made the point that this suite compares copies of the same public literals
 * against the same public implementation, so nothing here can detect drift against a NON-PUBLIC
 * producer. That is true, it is recorded as a non-claim (`NON-CLAIMS.md` §S6.2), and it is not
 * closable from inside this repository.
 *
 * What IS closable, and what this test closes, is the weaker failure that would make the whole
 * corpus worthless on its own terms: a pin that no longer decides anything. A hash constant sitting
 * in a file, printed in a report as evidence, while every assertion that reads it would pass just
 * as happily with a different value — that is decoration wearing evidence's clothes, and it is the
 * exact shape this repository's own lint-control-knockout gate exists to refuse elsewhere.
 *
 * So each pin is mutated by ONE CHARACTER and the check that depends on it must FAIL. A pin whose
 * mutation changes no verdict is reported by name.
 */
test("anti-vacuity: a one-character drift in ANY pin fails the check that rests on it", () => {
  /** Flip the last hex digit — the smallest possible drift, not an obviously-different value. */
  const drift = (hash: string): string => {
    const last = hash.slice(-1);
    return hash.slice(0, -1) + (last === "0" ? "1" : "0");
  };

  // 1. The two identity pins: a drifted pin must not equal the recomputed identity.
  const schemaRecomputed = projectionIdentityHash({
    id: "noa.deploy.release.schema", version: 1, kind: "actionSchema",
    implementation: DEPLOY_RELEASE_IMPLEMENTATION_DIGEST,
  });
  assert.equal(schemaRecomputed, PIN_SCHEMA_HASH, "control: the pin holds before it is drifted");
  assert.notEqual(schemaRecomputed, drift(PIN_SCHEMA_HASH),
    "the schema pin is not load-bearing — a drifted value still compares equal");

  const displayRecomputed = projectionIdentityHash({
    id: "noa.deploy.release.display", version: 1, kind: "displayProjection",
    implementation: DEPLOY_RELEASE_IMPLEMENTATION_DIGEST,
  });
  assert.equal(displayRecomputed, PIN_DISPLAY_HASH);
  assert.notEqual(displayRecomputed, drift(PIN_DISPLAY_HASH), "the display pin is not load-bearing");

  // 2. The implementation digest is an INPUT to both identities: drifting it must move both, or the
  //    identity does not actually commit to the artifact it names.
  const driftedImpl = drift(DEPLOY_RELEASE_IMPLEMENTATION_DIGEST);
  assert.notEqual(
    projectionIdentityHash({ id: "noa.deploy.release.schema", version: 1, kind: "actionSchema", implementation: driftedImpl }),
    PIN_SCHEMA_HASH,
    "a one-character change to the implementation digest left the schema identity unmoved — the " +
      "identity does not commit to the artifact digest at all",
  );
  assert.notEqual(
    projectionIdentityHash({ id: "noa.deploy.release.display", version: 1, kind: "displayProjection", implementation: driftedImpl }),
    PIN_DISPLAY_HASH,
    "a one-character change to the implementation digest left the display identity unmoved",
  );

  // 3. `kind` and `id` must each be load-bearing too: if either were ignored, two roles would share
  //    one identity and an envelope would pin a name that does not distinguish renderer from schema.
  assert.notEqual(
    projectionIdentityHash({ id: "noa.deploy.release.schema", version: 1, kind: "displayProjection", implementation: DEPLOY_RELEASE_IMPLEMENTATION_DIGEST }),
    PIN_SCHEMA_HASH, "`kind` does not affect the identity",
  );
  assert.notEqual(
    projectionIdentityHash({ id: "noa.deploy.release.display", version: 1, kind: "actionSchema", implementation: DEPLOY_RELEASE_IMPLEMENTATION_DIGEST }),
    PIN_SCHEMA_HASH, "`id` does not affect the identity",
  );
  assert.notEqual(
    projectionIdentityHash({ id: "noa.deploy.release.schema", version: 2, kind: "actionSchema", implementation: DEPLOY_RELEASE_IMPLEMENTATION_DIGEST }),
    PIN_SCHEMA_HASH, "`version` does not affect the identity",
  );

  // 4. The paramsHash pin: the real tuple must not match a drifted pin.
  const r = run(baseParams());
  assert.ok(r.ok);
  assert.equal(r.paramsHash, PIN_PARAMS_HASH, "control: the pin holds before it is drifted");
  assert.notEqual(r.paramsHash, drift(PIN_PARAMS_HASH), "the paramsHash pin is not load-bearing");

  // 5. And the corpus's own copies must equal these literals — the check that would catch a
  //    regenerated corpus quietly disagreeing with the specification's published values.
  const identities = corpus.vectors.filter(isIdentity);
  const schemaVec = identities.find((v) => v.name === "identity-action-schema");
  const displayVec = identities.find((v) => v.name === "identity-display");
  assert.ok(schemaVec && displayVec, "both identity vectors must be present in the corpus");
  assert.equal(schemaVec.expect.hash, PIN_SCHEMA_HASH, "the corpus disagrees with the specification's schema pin");
  assert.equal(displayVec.expect.hash, PIN_DISPLAY_HASH, "the corpus disagrees with the specification's display pin");
  assert.equal(corpus.implementationDigest, DEPLOY_RELEASE_IMPLEMENTATION_DIGEST);
  const validVec = corpus.vectors.filter((v) => !isIdentity(v)).find((v) => v.name === "valid") as ParamsVector;
  assert.ok(validVec, "the corpus must carry the `valid` accept vector");
  assert.equal(validVec.expect.paramsHash, PIN_PARAMS_HASH, "the corpus disagrees with the specification's paramsHash pin");
});
