/**
 * `noa.ledger.transfer/1` — the committed conformance corpus, plus the properties a fixture file
 * alone cannot state.
 *
 * THE CORPUS (conformance/ledger-transfer/vectors.json) is generated by
 * `scripts/gen-ledger-transfer-vectors.ts`, which replays every vector before writing. This suite
 * re-runs the COMMITTED file independently, so a stale or hand-edited corpus fails here even if the
 * generator was never re-run. The corpus replay comes first in this file on purpose: when a control
 * is knocked out, the first failures reported are the named vectors that measure it.
 *
 * THE PINS below are restated as literals, independently of the module's constants and of the
 * generator's copy, so implementation, corpus, generator and suite must all agree before anything is
 * green. They are normative expected values, not an attestation from any running system
 * (`NON-CLAIMS.md` §S7). The anti-vacuity test drifts each pin by one character and requires the
 * check that rests on it to fail.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  LEDGER_TRANSFER_SPEC,
  LEDGER_TRANSFER_CANONICAL,
  LEDGER_TRANSFER_IMPLEMENTATION_DIGEST,
  LEDGER_TRANSFER_SCHEMA_ID,
  LEDGER_TRANSFER_DISPLAY_ID,
  projectLedgerTransfer,
  type LedgerTransferResult,
  type LedgerTransferRefusalCode,
} from "../src/ledger-transfer.js";
import { projectionIdentityHash } from "../src/deploy-release.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const funcToString = Function.prototype.toString;

// ── THE NORMATIVE PINS, restated independently ───────────────────────────────────────────────────
const PIN_IMPLEMENTATION = "sha256:2f4dce6dce395e77b93ecec4c19f2d34d303fa07d198a8464d254a1561423039";
const PIN_SCHEMA_HASH = "sha256:f34d508cfa9080eadaa771ed8852a0d34c09246d03f818d75f848abb4df25901";
const PIN_DISPLAY_HASH = "sha256:bb6e72d64700383a4ceabefeb8e8eb170a2877ca95a5522c90901466e9a421db";
const PIN_PARAMS_HASH = "sha256:aa9256899837f204583f28e483ed67129b204e7edabf378eaf60f296915aebd0";

/**
 * The eleven codes of /1 and their position in the normative refusal order. A Record over the
 * published `LedgerTransferRefusalCode` union: a code missing here, or one the union does not name,
 * is a compile error — the list is tied to the type rather than restated beside it.
 */
const CODE_ORDER: Readonly<Record<LedgerTransferRefusalCode, number>> = {
  TRANSFER_PARSE: 0,
  TRANSFER_NOT_OBJECT: 1,
  TRANSFER_AMOUNT_INVALID: 2,
  TRANSFER_FROM_INVALID: 3,
  TRANSFER_LEDGER_INVALID: 4,
  TRANSFER_SALT_INVALID: 5,
  TRANSFER_TO_INVALID: 6,
  TRANSFER_UNIT_INVALID: 7,
  TRANSFER_UNRECOGNIZED_MEMBER: 8,
  TRANSFER_SAME_ACCOUNT: 9,
  TRANSFER_CANONICAL_REPARSE: 10,
};
const CODES: readonly LedgerTransferRefusalCode[] =
  (Object.keys(CODE_ORDER) as LedgerTransferRefusalCode[]).sort((a, b) => CODE_ORDER[a] - CODE_ORDER[b]);

// ── THE FIXTURE, SYNTHETIC BY CONSTRUCTION, SPELLED ONCE ─────────────────────────────────────────
const ACCT_1 = "acct-example-1";
const ACCT_2 = "acct-example-2";
const LEDGER_1 = "ledger-example-1";
const SALT_A = "000102030405060708090a0b0c0d0e0f";
const MEMBERS = ["amount", "fromAccount", "ledger", "salt", "toAccount", "unit"] as const;
const MEMBER_CODE: Readonly<Record<(typeof MEMBERS)[number], LedgerTransferRefusalCode>> = {
  amount: "TRANSFER_AMOUNT_INVALID",
  fromAccount: "TRANSFER_FROM_INVALID",
  ledger: "TRANSFER_LEDGER_INVALID",
  salt: "TRANSFER_SALT_INVALID",
  toAccount: "TRANSFER_TO_INVALID",
  unit: "TRANSFER_UNIT_INVALID",
};

function baseParams(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return { amount: "12345", fromAccount: ACCT_1, ledger: LEDGER_1, salt: SALT_A, toAccount: ACCT_2, unit: "XTS", ...overrides };
}
const run = (params: unknown): LedgerTransferResult => projectLedgerTransfer(JSON.stringify(params));
const enc = new TextEncoder();

// ── THE CORPUS ───────────────────────────────────────────────────────────────────────────────────
interface IdentityVector {
  name: string;
  note: string;
  descriptor: { id: string; version: number; kind: "actionSchema" | "displayProjection"; implementation: string };
  expect: { hash: string };
}
interface ParamsVector {
  name: string;
  group: string;
  note: string;
  paramsText?: string;
  paramsHex?: string;
  equivalentTo?: string;
  beats?: string;
  expect: {
    ok: boolean;
    paramsHash?: string;
    canonical?: string;
    display?: Record<string, string>;
    reasonCode?: string;
    reasonContains?: string;
  };
}
interface Corpus {
  spec: string;
  canonical: string;
  generatedFrom: string;
  implementationDigest: string;
  refusalCodes: string[];
  vectors: Array<IdentityVector | ParamsVector>;
}

const corpus = JSON.parse(
  readFileSync(join(ROOT, "conformance", "ledger-transfer", "vectors.json"), "utf8"),
) as Corpus;
const isIdentity = (v: IdentityVector | ParamsVector): v is IdentityVector =>
  (v as IdentityVector).descriptor !== undefined;
const paramsVectors = corpus.vectors.filter((v) => !isIdentity(v)) as ParamsVector[];
const inputOf = (v: ParamsVector): string | Uint8Array =>
  typeof v.paramsText === "string" ? v.paramsText : Uint8Array.from(Buffer.from(v.paramsHex as string, "hex"));

for (const vec of corpus.vectors) {
  if (isIdentity(vec)) {
    test(`ledger-transfer/${vec.name} → identity recomputes from its descriptor`, () => {
      assert.equal(projectionIdentityHash(vec.descriptor), vec.expect.hash);
    });
    continue;
  }
  test(`ledger-transfer/${vec.name} → ${vec.expect.ok ? "ACCEPT" : `REJECT ${vec.expect.reasonCode}`}`, () => {
    const forms: Array<string | Uint8Array> = [inputOf(vec)];
    // The text and byte entry points must agree on every text vector.
    if (typeof vec.paramsText === "string") forms.push(enc.encode(vec.paramsText));
    for (const input of forms) {
      const res = projectLedgerTransfer(input);
      assert.equal(res.ok, vec.expect.ok, res.ok ? `expected ${vec.expect.reasonCode}, got ACCEPT` : `unexpected refusal: ${res.reason}`);
      if (!res.ok) {
        assert.equal(res.code, vec.expect.reasonCode, `${vec.name}: refused for the WRONG reason: ${res.reason}`);
        assert.ok(res.reason.startsWith(`${res.code}: `), `${vec.name}: the reason must begin with its code`);
        if (vec.expect.reasonContains !== undefined) {
          assert.ok(res.reason.includes(vec.expect.reasonContains), `${vec.name}: kernel reason drifted: ${res.reason}`);
        }
      } else {
        assert.equal(res.paramsHash, vec.expect.paramsHash);
        assert.equal(res.canonical, vec.expect.canonical);
        assert.deepEqual({ ...res.display }, vec.expect.display);
      }
    }
  });
}

test("the corpus is the shape the runner expects and covers every class", () => {
  assert.equal(corpus.spec, LEDGER_TRANSFER_SPEC);
  assert.equal(corpus.canonical, LEDGER_TRANSFER_CANONICAL);
  assert.equal(corpus.implementationDigest, LEDGER_TRANSFER_IMPLEMENTATION_DIGEST);
  assert.equal(corpus.generatedFrom, "scripts/gen-ledger-transfer-vectors.ts");
  assert.deepEqual(corpus.refusalCodes, CODES, "the published code list is exactly the eleven codes of /1, in order");

  const counts: Record<string, number> = {};
  for (const v of paramsVectors) counts[v.group] = (counts[v.group] ?? 0) + 1;
  assert.deepEqual(counts, {
    accept: 20, parse: 12, "not-object": 5, amount: 21, from: 21, ledger: 7, to: 7, unit: 8, salt: 8,
    unrecognized: 14, "same-account": 2, precedence: 9,
  });
  assert.equal(corpus.vectors.filter(isIdentity).length, 2);

  const seen = new Set<string>();
  for (const v of paramsVectors) {
    assert.ok(!seen.has(v.name), `duplicate vector name ${v.name}`);
    seen.add(v.name);
    assert.ok((typeof v.paramsText === "string") !== (typeof v.paramsHex === "string"), `${v.name}: exactly one of paramsText / paramsHex`);
    if (v.expect.ok) {
      assert.match(String(v.expect.paramsHash), /^sha256:[0-9a-f]{64}$/, `${v.name}: accept must pin its paramsHash`);
      assert.equal(typeof v.expect.canonical, "string", `${v.name}: accept must pin its canonical bytes`);
      assert.equal(Object.keys(v.expect.display ?? {}).length, 6, `${v.name}: accept must pin the full six-row display`);
    } else {
      assert.ok((CODES as readonly string[]).includes(String(v.expect.reasonCode)), `${v.name}: unknown code ${v.expect.reasonCode}`);
      if (v.expect.reasonCode === "TRANSFER_PARSE") {
        assert.ok((v.expect.reasonContains ?? "").length > 0, `${v.name}: a parse vector must pin the kernel reason`);
      } else {
        assert.equal(v.expect.reasonContains, undefined, `${v.name}: only parse vectors pin reason text`);
      }
    }
  }
  assert.ok(paramsVectors.filter((v) => typeof v.paramsHex === "string").length <= 2, "at most two byte-level vectors");

  // Every reachable code has a vector; the render-node guard has none (no input reaches it).
  const codes = new Set<string | undefined>(paramsVectors.filter((v) => !v.expect.ok).map((v) => v.expect.reasonCode));
  for (const c of CODES) {
    if (c === "TRANSFER_CANONICAL_REPARSE") assert.ok(!codes.has(c), "the render-node guard must be unreachable");
    else assert.ok(codes.has(c), `no vector exercises ${c}`);
  }
});

test("accept vectors bind pairwise-distinct transfers, except the declared equivalents", () => {
  const accepts = paramsVectors.filter((v) => v.expect.ok);
  const byName = new Map(accepts.map((v) => [v.name, v]));
  const hashes = new Set<string>();
  const displays = new Set<string>();
  for (const v of accepts) {
    if (v.equivalentTo !== undefined) {
      const target = byName.get(v.equivalentTo);
      assert.ok(target, `${v.name}: equivalentTo must name an accept vector`);
      assert.equal(v.expect.paramsHash, target.expect.paramsHash);
      assert.equal(v.expect.canonical, target.expect.canonical);
      assert.notEqual(v.paramsText, target.paramsText, `${v.name}: an equivalent must be a DIFFERENT input spelling`);
      continue;
    }
    assert.ok(!hashes.has(String(v.expect.paramsHash)), `${v.name}: two different transfers share a paramsHash`);
    hashes.add(String(v.expect.paramsHash));
    const shown = JSON.stringify(Object.entries(v.expect.display ?? {}).sort());
    assert.ok(!displays.has(shown), `${v.name}: two different transfers render the same display`);
    displays.add(shown);
  }
  assert.equal(accepts.filter((v) => v.equivalentTo === "accept-base").length, 3);
});

/** Remove exactly the violation `code` names from a parsed tuple (this suite's own repair, not the generator's). */
function repairViolation(o: Record<string, unknown>, code: string): Record<string, unknown> {
  const c: Record<string, unknown> = { ...o };
  const member = MEMBERS.find((m) => MEMBER_CODE[m] === code);
  if (member !== undefined) c[member] = baseParams()[member];
  else if (code === "TRANSFER_UNRECOGNIZED_MEMBER") {
    for (const k of Object.keys(c)) if (!(MEMBERS as readonly string[]).includes(k)) delete c[k];
  } else if (code === "TRANSFER_SAME_ACCOUNT") c["toAccount"] = c["fromAccount"] === ACCT_2 ? "acct-example-3" : ACCT_2;
  else assert.fail(`no repair for ${code}`);
  return c;
}

test("the corpus pins EVERY adjacent pair of the normative refusal order", () => {
  // The chain from the first member rule to the two-member rule, derived from the code order. If every
  // adjacent pair is pinned, an implementation that checks these rules in any other order inverts at
  // least one pinned pair and fails the corpus.
  const chain = CODES.slice(CODE_ORDER.TRANSFER_AMOUNT_INVALID, CODE_ORDER.TRANSFER_SAME_ACCOUNT + 1);
  assert.equal(chain.length, 8);
  const precedence = paramsVectors.filter((v) => v.beats !== undefined);
  for (let i = 0; i + 1 < chain.length; i++) {
    const [first, second] = [chain[i] as string, chain[i + 1] as string];
    const pin = precedence.find((v) => v.expect.reasonCode === first && v.beats === second);
    assert.ok(pin, `no precedence vector pins ${first} before ${second}`);
  }
  for (const v of precedence) {
    assert.equal(v.group, "precedence");
    assert.equal(v.expect.ok, false);
    // Both violations must really be present: repairing the winner yields the loser, and repairing
    // the loser still yields the winner. Parsed with JSON.parse — an independent read of the input.
    const parsed = JSON.parse(String(v.paramsText)) as Record<string, unknown>;
    const winner = String(v.expect.reasonCode);
    const loser = String(v.beats);
    assert.ok(CODE_ORDER[winner as LedgerTransferRefusalCode] < CODE_ORDER[loser as LedgerTransferRefusalCode], `${v.name}: winner must precede loser`);
    const r1 = run(repairViolation(parsed, winner));
    assert.ok(!r1.ok && r1.code === loser, `${v.name}: repairing ${winner} must leave ${loser}, got ${JSON.stringify(r1)}`);
    const r2 = run(repairViolation(parsed, loser));
    assert.ok(!r2.ok && r2.code === winner, `${v.name}: repairing ${loser} must leave ${winner}, got ${JSON.stringify(r2)}`);
  }
});

// ── THE PINS, AGAINST THE MODULE DIRECTLY ────────────────────────────────────────────────────────

test("the implementation digest is SHA-256 of the emitted projectLedgerTransfer source, recomputed here", () => {
  // A real in-repository check: the function ships in the published build, so the pin is not a bare
  // constant — this suite measures the artifact it names on every run.
  const source = funcToString.call(projectLedgerTransfer);
  assert.ok(source.length > 0 && !source.includes("[native code]"), "the artifact must be measurable");
  const measured = "sha256:" + createHash("sha256").update(source, "utf8").digest("hex");
  assert.equal(measured, PIN_IMPLEMENTATION,
    "projectLedgerTransfer's emitted text moved: say whether behaviour or the toolchain changed, then move " +
      "this pin, both identities and the corpus together");
  assert.equal(LEDGER_TRANSFER_IMPLEMENTATION_DIGEST, PIN_IMPLEMENTATION);
});

test("both identities recompute from their descriptors, and they differ", () => {
  assert.equal(LEDGER_TRANSFER_SCHEMA_ID.id, "noa.ledger.transfer.schema");
  assert.equal(LEDGER_TRANSFER_SCHEMA_ID.version, 1);
  assert.equal(LEDGER_TRANSFER_SCHEMA_ID.hash, PIN_SCHEMA_HASH);
  assert.equal(LEDGER_TRANSFER_DISPLAY_ID.id, "noa.ledger.transfer.display");
  assert.equal(LEDGER_TRANSFER_DISPLAY_ID.version, 1);
  assert.equal(LEDGER_TRANSFER_DISPLAY_ID.hash, PIN_DISPLAY_HASH);
  assert.equal(
    projectionIdentityHash({ id: "noa.ledger.transfer.schema", version: 1, kind: "actionSchema", implementation: PIN_IMPLEMENTATION }),
    PIN_SCHEMA_HASH,
  );
  assert.equal(
    projectionIdentityHash({ id: "noa.ledger.transfer.display", version: 1, kind: "displayProjection", implementation: PIN_IMPLEMENTATION }),
    PIN_DISPLAY_HASH,
  );
  assert.notEqual(PIN_SCHEMA_HASH, PIN_DISPLAY_HASH);
});

test("the conformance tuple binds the published paramsHash, deterministically", () => {
  const r1 = run(baseParams());
  const r2 = projectLedgerTransfer(enc.encode(JSON.stringify(baseParams())));
  assert.ok(r1.ok && r2.ok);
  assert.equal(r1.paramsHash, PIN_PARAMS_HASH);
  assert.equal(r2.paramsHash, PIN_PARAMS_HASH);
  assert.equal(r1.canonical, r2.canonical);
  assert.deepEqual({ ...r1.display }, { ...r2.display });
  assert.equal(r1.actionSchema, LEDGER_TRANSFER_SCHEMA_ID);
  assert.equal(r1.displayProjection, LEDGER_TRANSFER_DISPLAY_ID);
  // The hash is SHA-256 over the UTF-8 of `canonical` — recomputed here without the module's hash helper.
  assert.equal("sha256:" + createHash("sha256").update(r1.canonical, "utf8").digest("hex"), PIN_PARAMS_HASH);
});

// ── PROPERTIES THE CORPUS CANNOT STATE ───────────────────────────────────────────────────────────

/** Rows back to members — the offline-verifier procedure of spec §5.2 (deliberately not exported). */
function rebuild(display: Readonly<Record<string, string>>): Record<string, string> {
  const amountRow = String(display["Amount"]);
  const space = amountRow.indexOf(" ");
  assert.ok(space > 0 && amountRow.indexOf(" ", space + 1) < 0, "Amount is exactly `<digits> <unit>`");
  return {
    amount: amountRow.slice(0, space),
    fromAccount: String(display["From"]),
    ledger: String(display["Ledger"]),
    salt: String(display["Salt"]),
    toAccount: String(display["To"]),
    unit: amountRow.slice(space + 1),
  };
}

test("display completeness: every bound value is visible, nothing unbound is shown, and the rows rebuild the tuple", () => {
  const tuples = [
    baseParams(),
    baseParams({ amount: "1" }),
    baseParams({ amount: "9".repeat(15), salt: "f".repeat(32) }),
    baseParams({ fromAccount: "a".repeat(64), toAccount: "a-1-b", ledger: "z" }),
  ];
  for (const t of tuples) {
    const r = run(t);
    assert.ok(r.ok, JSON.stringify(r));
    // Mechanical completeness: each bound VALUE appears verbatim in the rendering. A hand-written
    // expectation stops being a completeness check the day a row is dropped; this arm does not.
    const rendered = Object.values(r.display).join("\u0000");
    for (const m of MEMBERS) {
      assert.ok(rendered.includes(String(t[m])), `bound member \`${m}\` is not visible to the approver`);
    }
    assert.deepEqual(Object.keys(r.display).sort(), ["Action", "Amount", "From", "Ledger", "Salt", "To"],
      "exactly six rows: every bound member visible and nothing unbound shown");
    assert.equal(r.display["Action"], LEDGER_TRANSFER_CANONICAL);
    // Completeness in the strong sense: the tuple is recoverable from the rows alone, and the rebuilt
    // tuple re-projects to the SAME hash — the check an auditor runs on an audit-decrypted display.
    const rebuilt = rebuild(r.display);
    assert.deepEqual(rebuilt, { ...r.value });
    const again = run(rebuilt);
    assert.ok(again.ok && again.paramsHash === r.paramsHash, "the rebuilt tuple must bind the same hash");
  }
});

test("display injectivity: different transfers never render the same rows", () => {
  const tuples = [
    baseParams(),
    baseParams({ fromAccount: ACCT_2, toAccount: ACCT_1 }), // direction swap
    baseParams({ amount: "1234" }),
    baseParams({ amount: "123456" }),
    baseParams({ fromAccount: "acct-example-12" }), // prefix of nothing, extension of ACCT_1
    baseParams({ toAccount: "acct-example" }), // prefix of the accounts
    baseParams({ ledger: "ledger-example-10" }),
    baseParams({ salt: SALT_A.slice(0, 31) + "e" }),
  ];
  const displays = new Set<string>();
  const hashes = new Set<string>();
  for (const t of tuples) {
    const r = run(t);
    assert.ok(r.ok, JSON.stringify(r));
    displays.add(JSON.stringify(Object.entries(r.display).sort()));
    hashes.add(r.paramsHash);
  }
  assert.equal(hashes.size, tuples.length, "each tuple is a different transfer");
  assert.equal(displays.size, tuples.length, "two different transfers rendered the same rows");
});

test("every single-member change moves the digest (exact authority permits only the exact attempt)", () => {
  const hashes = [
    run(baseParams()),
    run(baseParams({ amount: "12346" })),
    run(baseParams({ fromAccount: "acct-example-3" })),
    run(baseParams({ ledger: "ledger-example-2" })),
    run(baseParams({ salt: SALT_A.slice(0, 31) + "e" })),
    run(baseParams({ toAccount: "acct-example-3" })),
  ].map((r) => {
    assert.ok(r.ok, JSON.stringify(r));
    return r.paramsHash;
  });
  assert.equal(new Set(hashes).size, hashes.length);
});

test("the accepted key set is EXACTLY the six: removing one names it, adding one is refused", () => {
  assert.equal((run(baseParams()) as { paramsHash?: string }).paramsHash, PIN_PARAMS_HASH, "control: the clean tuple is accepted");
  for (const m of MEMBERS) {
    const p = baseParams();
    delete p[m];
    const r = run(p);
    assert.ok(!r.ok && r.code === MEMBER_CODE[m], `removing \`${m}\` must refuse with ${MEMBER_CODE[m]}, got ${JSON.stringify(r)}`);
  }
  for (const junk of ["memo", "fee", "x", "__proto__x", "Amount", " amount", "amount2", "from", "to", "currency", "scale"]) {
    const r = run({ ...baseParams(), [junk]: "1" });
    assert.ok(!r.ok && r.code === "TRANSFER_UNRECOGNIZED_MEMBER", `\`${junk}\` must be refused as unrecognized, got ${JSON.stringify(r)}`);
  }
});

test("range bounds hold on both sides", () => {
  const ok = (o: Record<string, unknown>): boolean => run(baseParams(o)).ok;
  assert.equal(ok({ amount: "1" }), true);
  assert.equal(ok({ amount: "9".repeat(15) }), true);
  assert.equal(ok({ amount: "0" }), false);
  assert.equal(ok({ amount: "1" + "0".repeat(15) }), false, "16 digits is past the bound");
  assert.ok(Number("9".repeat(15)) < Number.MAX_SAFE_INTEGER, "the largest amount is exact in binary64");
  for (const m of ["fromAccount", "ledger", "toAccount"]) {
    assert.equal(ok({ [m]: "q".repeat(64) }), true, `${m}: 64 is the bound, not 63`);
    assert.equal(ok({ [m]: "q".repeat(65) }), false, `${m}: 65 is past the bound`);
    assert.equal(ok({ [m]: "q" }), true, `${m}: one character is legal`);
  }
  assert.equal(ok({ salt: "a".repeat(32) }), true);
  assert.equal(ok({ salt: "a".repeat(31) }), false);
  assert.equal(ok({ salt: "a".repeat(33) }), false);
});

test("the closed unit enum: exactly {XTS} accepts, and nothing else does", () => {
  const candidates = ["XTS", "xts", "Xts", "XTS ", " XTS", "", "USD", "EUR", "XXX", "XAU", "__proto__", "constructor", "toString", "ХTS"];
  const accepted = candidates.filter((u) => run(baseParams({ unit: u })).ok);
  assert.deepEqual(accepted, ["XTS"], "the runtime table and the published LedgerTransferUnit type must not diverge");
});

test("a self-transfer is refused after parsing, and only when the two accounts are the same", () => {
  const r1 = run(baseParams({ toAccount: ACCT_1 }));
  assert.ok(!r1.ok && r1.code === "TRANSFER_SAME_ACCOUNT");
  const r2 = run(baseParams({ toAccount: "acct-example-10" }));
  assert.ok(r2.ok, "an account whose id EXTENDS the source is a different account");
});

test("a caller-owned object is refused without being traversed (bytes in)", () => {
  let reads = 0;
  const hostile: Record<string, unknown> = { ...baseParams() };
  Object.defineProperty(hostile, "amount", { enumerable: true, get() { reads++; return "12345"; } });
  const r = projectLedgerTransfer(hostile as unknown as string);
  assert.equal(reads, 0, "the getter must never fire");
  assert.ok(!r.ok && r.code === "TRANSFER_PARSE");
});

test("results are inert: value, display and identities are frozen and null-rooted", () => {
  const r = run(baseParams());
  assert.ok(r.ok);
  for (const o of [r.value, r.display, LEDGER_TRANSFER_SCHEMA_ID, LEDGER_TRANSFER_DISPLAY_ID]) {
    assert.ok(Object.isFrozen(o));
    assert.equal(Object.getPrototypeOf(o), null);
  }
  assert.throws(() => { (r.display as Record<string, string>)["Amount"] = "1 XTS"; }, TypeError);
  assert.throws(() => { (LEDGER_TRANSFER_SCHEMA_ID as { hash: string }).hash = "sha256:" + "0".repeat(64); }, TypeError);
});

test("for every accept, the pinned canonical bytes equal the template built from the INPUT, not from the output", () => {
  // Independent read path: the vector's input text through JSON.parse (not the kernel's parser, not
  // the implementation's returned tuple), then the §4.3 template, compared with the pinned bytes.
  const accepts = paramsVectors.filter((x) => x.expect.ok);
  assert.equal(accepts.length, 20);
  for (const v of accepts) {
    const p = JSON.parse(String(v.paramsText)) as Record<string, unknown>;
    assert.deepEqual(Object.keys(p).sort(), [...MEMBERS], `${v.name}: an accept input carries exactly the six members`);
    for (const m of MEMBERS) assert.equal(typeof p[m], "string", `${v.name}: ${m} is a string`);
    const template =
      `{"amount":"${p["amount"]}","fromAccount":"${p["fromAccount"]}","ledger":"${p["ledger"]}",` +
      `"salt":"${p["salt"]}","toAccount":"${p["toAccount"]}","unit":"${p["unit"]}"}`;
    assert.equal(v.expect.canonical, template, `${v.name}: the pinned canonical bytes must equal the input's template`);
    assert.equal(v.expect.paramsHash, "sha256:" + createHash("sha256").update(template, "utf8").digest("hex"),
      `${v.name}: the pinned paramsHash must be SHA-256 of that template`);
  }
});

/**
 * ANTI-VACUITY: EVERY PIN IS LOAD-BEARING. Each pin is drifted by one character and the check that
 * rests on it must fail. A pin whose drift changes no verdict is decoration printed as evidence.
 */
test("anti-vacuity: a one-character drift in ANY pin fails the check that rests on it", () => {
  const drift = (hash: string): string => {
    const last = hash.slice(-1);
    return hash.slice(0, -1) + (last === "0" ? "1" : "0");
  };
  // Whether the module's own implementation pin is load-bearing is measured mechanically by the
  // `ledger-transfer-implementation-pin` knockout (scripts/lint-control-knockout.mjs), which drifts it
  // by one character and requires this file to go red. What is checked here can fail on its own.
  const schema = (impl: string, kind: "actionSchema" | "displayProjection" = "actionSchema", id = "noa.ledger.transfer.schema", version = 1) =>
    projectionIdentityHash({ id, version, kind, implementation: impl });
  assert.equal(schema(PIN_IMPLEMENTATION), PIN_SCHEMA_HASH, "control");
  assert.notEqual(schema(drift(PIN_IMPLEMENTATION)), PIN_SCHEMA_HASH, "the identity does not commit to the implementation digest");
  assert.notEqual(schema(PIN_IMPLEMENTATION, "displayProjection"), PIN_SCHEMA_HASH, "`kind` does not affect the identity");
  assert.notEqual(schema(PIN_IMPLEMENTATION, "actionSchema", "noa.ledger.transfer.display"), PIN_SCHEMA_HASH, "`id` does not affect the identity");
  assert.notEqual(schema(PIN_IMPLEMENTATION, "actionSchema", "noa.ledger.transfer.schema", 2), PIN_SCHEMA_HASH, "`version` does not affect the identity");

  // Every published copy of every pin agrees: the normative text states all four values verbatim, and
  // an implementer reading the specification must reach the same bytes this suite checks.
  const spec = readFileSync(join(ROOT, "docs", "ledger-transfer-spec.md"), "utf8");
  for (const pin of [PIN_IMPLEMENTATION, PIN_SCHEMA_HASH, PIN_DISPLAY_HASH, PIN_PARAMS_HASH]) {
    assert.ok(spec.includes(pin), `the specification does not state the pin ${pin}`);
    assert.ok(!spec.includes(drift(pin)), `the specification states a drifted copy of ${pin}`);
  }

  // The corpus's own copies must equal these literals.
  const schemaVec = corpus.vectors.find((v) => v.name === "identity-action-schema") as IdentityVector | undefined;
  const displayVec = corpus.vectors.find((v) => v.name === "identity-display") as IdentityVector | undefined;
  const baseVec = paramsVectors.find((v) => v.name === "accept-base");
  assert.equal(schemaVec?.expect.hash, PIN_SCHEMA_HASH);
  assert.equal(displayVec?.expect.hash, PIN_DISPLAY_HASH);
  assert.equal(schemaVec?.descriptor.implementation, PIN_IMPLEMENTATION);
  assert.equal(baseVec?.expect.paramsHash, PIN_PARAMS_HASH);
});
