/**
 * NOA Gate — per-agent bearer auth (spec §8: "per-agent API key, constant-time compare").
 *
 * The wrapper / agent authenticates with `Authorization: Bearer noa_gateagent_<secret>`. Only the
 * sha256 HASH of the secret is stored; the lookup compares hashes (constant-time inside node's
 * Map/`timingSafeEqual`). This is a TRANSPORT credential — it is NOT a signing key and grants no
 * ability to forge any gate-signed artifact (those need the gate's Ed25519 private key).
 */

import { createHash, timingSafeEqual } from "node:crypto";

export interface ParsedBearer {
  secret: string;
}

const AGENT_PREFIX = "noa_gateagent_";

export function parseBearer(authHeader: string | undefined): ParsedBearer | null {
  if (!authHeader) return null;
  const value = authHeader.trim();
  if (value.slice(0, "Bearer".length).toLowerCase() !== "bearer") return null;
  let tokenStart = "Bearer".length;
  if (tokenStart >= value.length || (value.charCodeAt(tokenStart) !== 0x20 && value.charCodeAt(tokenStart) !== 0x09)) return null;
  while (tokenStart < value.length && (value.charCodeAt(tokenStart) === 0x20 || value.charCodeAt(tokenStart) === 0x09)) tokenStart++;
  const token = value.slice(tokenStart);
  if (!token) return null;
  for (let i = 0; i < token.length; i++) {
    const code = token.charCodeAt(i);
    // HTTP bearer credentials are visible ASCII. Reject every whitespace/control byte, DEL and
    // non-ASCII code point so an accepted credential can never carry a second header/log line.
    if (code <= 0x20 || code >= 0x7f) return null;
  }
  if (token.startsWith(AGENT_PREFIX) && token.length > AGENT_PREFIX.length) {
    return { secret: token };
  }
  return null;
}

/** sha256 hex of a bearer secret. The plaintext secret is never persisted. */
export function hashSecret(secret: string): string {
  // These are uniformly random 192-bit bearer credentials generated by engine.ts, not
  // human-memorable passwords. A fast one-way lookup digest is therefore intentional: the input
  // already has more entropy than a password KDF can add, and request authentication must remain
  // DoS-resistant. Plaintext credentials are never persisted.
  // codeql[js/insufficient-password-hash]
  return createHash("sha256").update(secret, "utf8").digest("hex");
}

/** Constant-time compare of two lowercase-hex strings of equal length. Length-mismatch → false. */
export function constantTimeEqualHex(a: string, b: string): boolean {
  if (typeof a !== "string" || typeof b !== "string") return false;
  if (a.length !== b.length) return false;
  const ab = Buffer.from(a, "hex");
  const bb = Buffer.from(b, "hex");
  if (ab.length !== bb.length || ab.length === 0) return false;
  return timingSafeEqual(ab, bb);
}
