// ────────────────────────────────────────────────────────────────────────────────────────────────
// GENERATED FILE — DO NOT EDIT. Source of truth: noa-receipt/src/keys.ts (the marked strict-Ed25519 region only)
// Regenerate with:  node scripts/sync-inert-core.mjs      (CI runs --check and fails on drift)
//
// This package is zero-runtime-dependency by design, so the inert-data boundary is VENDORED rather
// than imported. It is generated, not ported: a hand-maintained copy is how "a rule enforced in
// some implementations" stops being an invariant.
// ────────────────────────────────────────────────────────────────────────────────────────────────

import { bufferFrom, bufToString, byteLength, mapGet, mapSet, mapSize, newMap, toBigInt } from "./intrinsics.js";
import { membership } from "./inert.js";

// ── BEGIN SHARED STRICT-ED25519 RULE ─────────────────────────────────────────────────────────────
// Generated byte-for-byte into packages/approval-artifacts/src/inert-core/ed25519-strict.ts by
// scripts/sync-inert-core.mjs; CI (`npm run check:inert-core`) fails when the copy drifts. Everything
// between the BEGIN and END lines uses only bufferFrom, bufToString, byteLength, mapGet, mapSet,
// mapSize, newMap, toBigInt (./intrinsics.js) and membership (./inert.js).
const isSmallOrderPubkey = membership([
  "0100000000000000000000000000000000000000000000000000000000000000", // order 1 (identity)
  "ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", // order 2
  "0000000000000000000000000000000000000000000000000000000000000000", // order 4
  "0000000000000000000000000000000000000000000000000000000000000080", // order 4
  "26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc05", // order 8
  "26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc85", // order 8
  "c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac037a", // order 8
  "c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac03fa", // order 8
]);

/** Field prime p = 2^255 - 19. */
const P25519 = (1n << 255n) - 19n;
/** Edwards curve constant d = -121665/121666 mod p (RFC 8032 §5.1). */
const D25519 = 37095705934669439343138083508754565189542113879843219016388785533085940283555n;
/** sqrt(-1) mod p = 2^((p-1)/4) mod p (RFC 8032 §5.1.3 step 3). */
const SQRT_M1_25519 = 19681161376707505956807079304988542015446066515923890162744021073123829784752n;
/** Prime group order L = 2^252 + 27742317777372353535851937790883648493 (RFC 8032 §5.1). */
const L25519 = (1n << 252n) + 27742317777372353535851937790883648493n;

/** Non-negative residue mod p. */
function fieldMod(a: bigint): bigint {
  const r = a % P25519;
  return r < 0n ? r + P25519 : r;
}

/** base^exp mod m by square-and-multiply. BigInt operators only — no bare global is called. */
function modPow(base: bigint, exp: bigint, m: bigint): bigint {
  let result = 1n;
  let b = base % m;
  let e = exp;
  while (e > 0n) {
    if ((e & 1n) === 1n) result = (result * b) % m;
    b = (b * b) % m;
    e >>= 1n;
  }
  return result;
}

/**
 * Strict RFC 8032 §5.1.3 decoding of a 32-byte point encoding. Returns the affine point as a
 * two-element array [x, y] (indexed, never destructured), or null when:
 *   1. the y coordinate (the low 255 bits) is not canonical (y >= p);
 *   2. y does not decode to a curve point (x^2 = (y^2 - 1) / (d*y^2 + 1) has no square root);
 *   3. x = 0 and the sign bit is set ("If x = 0, and x_0 = 1, decoding fails").
 * After these steps every accepted encoding is the one canonical encoding of its point.
 */
function decodeStrictEd25519Point(raw: Uint8Array): bigint[] | null {
  if (byteLength(raw) !== 32) return null;
  const xSign = (raw[31]! & 0x80) !== 0;
  const yBytes = bufferFrom(raw);
  yBytes[31] = yBytes[31]! & 0x7f;
  let y = 0n;
  // T18: `BigInt` is a bare global; building y through it would let `globalThis.BigInt = () => 0n`
  // collapse every point to y = 0. The captured `toBigInt` keeps this gate independent of the global.
  for (let i = 31; i >= 0; i--) y = (y << 8n) | toBigInt(yBytes[i]!);
  // 1. Canonical y. OpenSSL accepts a y >= p encoding AND re-exports it unchanged, so an SPKI
  //    round-trip cannot catch it.
  if (y >= P25519) return null;
  // 2. Recover x (RFC 8032 §5.1.3 steps 2-3).
  const y2 = (y * y) % P25519;
  const u = fieldMod(y2 - 1n);
  const v = (D25519 * y2 + 1n) % P25519;
  const v3 = (((v * v) % P25519) * v) % P25519;
  const v7 = (((v3 * v3) % P25519) * v) % P25519;
  let x = (((u * v3) % P25519) * modPow((u * v7) % P25519, (P25519 - 5n) / 8n, P25519)) % P25519;
  const vx2 = (v * ((x * x) % P25519)) % P25519;
  if (vx2 !== u) {
    if (vx2 !== fieldMod(-u)) return null;
    x = (x * SQRT_M1_25519) % P25519;
  }
  // 3. x = 0 with the sign bit set is not a valid encoding.
  if (x === 0n && xSign) return null;
  if (((x & 1n) === 1n) !== xSign) x = P25519 - x;
  return [x, y];
}

/** RFC 8032 §5.1.4 addition on extended coordinates [X, Y, Z, T]; complete, so also used to double. */
function extendedAdd(p: bigint[], q: bigint[]): bigint[] {
  const a = ((p[1]! - p[0]!) * (q[1]! - q[0]!)) % P25519;
  const b = ((p[1]! + p[0]!) * (q[1]! + q[0]!)) % P25519;
  const c = (((2n * p[3]!) % P25519) * ((q[3]! * D25519) % P25519)) % P25519;
  const d = (((2n * p[2]!) % P25519) * q[2]!) % P25519;
  const e = b - a;
  const f = d - c;
  const g = d + c;
  const h = b + a;
  return [(e * f) % P25519, (g * h) % P25519, (f * g) % P25519, (e * h) % P25519];
}

/** Remembered step-5 results by key hex; replaced wholesale once it reaches its bound. */
let primeOrderSubgroupCache = newMap<string, boolean>();

/** True when [L]P is the identity, i.e. P lies in the prime-order subgroup (no torsion component). */
function isInPrimeOrderSubgroup(point: bigint[]): boolean {
  const base = [point[0]!, point[1]!, 1n, (point[0]! * point[1]!) % P25519];
  let acc = [0n, 1n, 1n, 0n];
  for (let i = 252n; i >= 0n; i--) {
    acc = extendedAdd(acc, acc);
    if (((L25519 >> i) & 1n) === 1n) acc = extendedAdd(acc, base);
  }
  return fieldMod(acc[0]!) === 0n && fieldMod(acc[1]! - acc[2]!) === 0n;
}

/**
 * STRICT PUBLIC-KEY VALIDATION for a raw 32-byte Ed25519 public key: refuse non-canonical and
 * small-order key encodings (RFC 8032 §5.1.3 decoding + small-order rejection), and keys outside
 * the prime-order subgroup. Every verifier in this repository applies the same rule at key load:
 *   1-3. strict decoding (decodeStrictEd25519Point);
 *   4. the point MUST NOT be one of the 8 small-order points (after 1-3 each has one encoding);
 *   5. the point MUST lie in the prime-order subgroup ([L]A = identity), which refuses mixed-order
 *      keys (a prime-order point plus a small-order component).
 * A key produced by Ed25519 key generation passes every step.
 */
export function isStrictEd25519PublicKeyBytes(raw: Uint8Array): boolean {
  const point = decodeStrictEd25519Point(raw);
  if (point === null) return false;
  const hex = bufToString(bufferFrom(raw), "hex");
  if (isSmallOrderPubkey(hex)) return false;
  // Step 5 costs one 253-bit scalar multiplication; its result is a pure function of the key bytes,
  // so it is remembered per key (bounded, captured Map methods only).
  const known = mapGet(primeOrderSubgroupCache, hex);
  if (known !== undefined) return known;
  const result = isInPrimeOrderSubgroup(point);
  if (mapSize(primeOrderSubgroupCache) >= 4096) primeOrderSubgroupCache = newMap<string, boolean>();
  mapSet(primeOrderSubgroupCache, hex, result);
  return result;
}

/**
 * STRICT SIGNATURE-R VALIDATION: the R half of an Ed25519 signature must be canonically encoded
 * (decoding steps 1-3 above) and MUST NOT be one of the 8 small-order points. With a prime-order key
 * and the cofactorless equation [S]B = R + [k]A, no R outside the prime-order subgroup can verify.
 */
export function isStrictEd25519SignatureRBytes(raw: Uint8Array): boolean {
  if (decodeStrictEd25519Point(raw) === null) return false;
  return !isSmallOrderPubkey(bufToString(bufferFrom(raw), "hex"));
}
// ── END SHARED STRICT-ED25519 RULE ───────────────────────────────────────────────────────────────
