/**
 * NOA Relay — bearer auth for non-signing calls.
 *
 * Agents authenticate with `Authorization: Bearer noa_agent_<secret>`, devices with
 * `noa_device_<secret>` (see the package README's endpoint and auth contract). Only the sha256 HASH of each secret is stored.
 *
 * ⚠ CORRECTED 2026-07-31 (claim finding C09). This line read "comparison is constant-time". It is
 * NOT, on this path: the bearer lookup is `store.ts:145-147`, a linear scan comparing with plain
 * `===` and returning early on a match. `constantTimeEqualHex` DOES exist in this file (:58) and IS
 * used — for the ENROLMENT SECRET, not for bearers. Three surfaces named a control that is not on
 * the path (this comment, and `packages/relay/README.md`).
 *
 * The wording is corrected rather than the code, deliberately: making the per-entry compare
 * constant-time would NOT make the sentence true, because the scan itself early-returns and its
 * duration is dominated by how many agents precede the match. Claiming constant-time for an
 * early-returning linear scan would replace one overclaim with another.
 *
 * WHAT THE COMPARISON IS OVER, which bounds the consequence: the stored value is a sha256 HASH, not
 * the secret. Timing information about a hash comparison yields hash-prefix knowledge, and turning
 * that into a usable bearer requires a preimage. This is a false CONTROL CLAIM, not an authorization
 * bypass. Tracked as P1 (C09), not P0.
 *
 * These secrets are session/bearer credentials for TRANSPORT — they
 * are NOT signing keys and grant no ability to forge a receipt (the phone's Ed25519 device key,
 * held only on-device, is the sole approval signer).
 */

import { createHash, timingSafeEqual } from "node:crypto";

export type BearerScheme = "agent" | "device";

export interface ParsedBearer {
  scheme: BearerScheme;
  secret: string;
}

const AGENT_PREFIX = "noa_agent_";
const DEVICE_PREFIX = "noa_device_";

export function parseBearer(authHeader: string | undefined): ParsedBearer | null {
  if (!authHeader) return null;
  const value = authHeader.trim();
  if (value.slice(0, "Bearer".length).toLowerCase() !== "bearer") return null;
  let tokenStart = "Bearer".length;
  if (tokenStart >= value.length || (value.charCodeAt(tokenStart) !== 0x20 && value.charCodeAt(tokenStart) !== 0x09)) return null;
  while (tokenStart < value.length && (value.charCodeAt(tokenStart) === 0x20 || value.charCodeAt(tokenStart) === 0x09)) tokenStart++;
  const token = value.slice(tokenStart);
  if (!token) return null;
  for (let i = 0; i < token.length; i++) {
    const code = token.charCodeAt(i);
    // HTTP bearer credentials are visible ASCII. Reject every whitespace/control byte, DEL and
    // non-ASCII code point so an accepted credential can never carry a second header/log line.
    if (code <= 0x20 || code >= 0x7f) return null;
  }
  if (token.startsWith(AGENT_PREFIX) && token.length > AGENT_PREFIX.length) {
    return { scheme: "agent", secret: token };
  }
  if (token.startsWith(DEVICE_PREFIX) && token.length > DEVICE_PREFIX.length) {
    return { scheme: "device", secret: token };
  }
  return null;
}

/** sha256 hex of a bearer secret. The plaintext secret is never persisted. */
export function hashSecret(secret: string): string {
  // These are uniformly random 192-bit bearer credentials generated by engine.ts, not
  // human-memorable passwords. A fast one-way lookup digest is therefore intentional: the input
  // already has more entropy than a password KDF can add, and request authentication must remain
  // DoS-resistant. Plaintext credentials are never persisted.
  // codeql[js/insufficient-password-hash]
  return createHash("sha256").update(secret, "utf8").digest("hex");
}

/** Constant-time compare of two lowercase-hex strings of equal length. Length-mismatch → false. */
export function constantTimeEqualHex(a: string, b: string): boolean {
  if (typeof a !== "string" || typeof b !== "string") return false;
  if (a.length !== b.length) return false;
  const ab = Buffer.from(a, "hex");
  const bb = Buffer.from(b, "hex");
  if (ab.length !== bb.length || ab.length === 0) return false;
  return timingSafeEqual(ab, bb);
}
