// ── NO LIVE `node:crypto` BINDING SURVIVES IN THIS FILE (T17, 2026-07-29) ─────────────────────────
// The previous round moved `createPublicKey` into `./intrinsics.js` and wrote the reason six lines
// above the four bindings it left behind: an ESM import binding for a builtin is REPOINTABLE by
// `syncBuiltinESMExports()`. `verify` was one of those four and it was **the** signature verdict, so
// `crypto.verify = () => true` + one `syncBuiltinESMExports()` turned a garbage 64-byte signature
// into VALID under an honest keyring. The fix is not "capture verify too" — it is that this file may
// not hold a live builtin binding at all, which `lint-security-gates.mjs` L8 now enforces for every
// TCB file so the next author cannot re-open the class by adding one import.
import {
  bufferFrom, bufToString, bufEquals, bufSubarray, byteLength,
  createPublicKeyCaptured, keyExportSpkiDer, keyExportPkcs8Der,
  createPrivateKeyCaptured, generateEd25519KeyPair, ed25519Sign, ed25519Verify,
  asymmetricKeyType, toBigInt, mapGet, mapSet, mapSize, newMap,
} from "./intrinsics.js";
import { membership } from "./inert.js";

/**
 * Ed25519 key handling for receipt signatures.
 *
 * Keys are carried as base64-encoded DER (SPKI for public, PKCS8 for private) so they are
 * a single opaque string in keyrings and config — no manual ASN.1, no raw-key
 * reconstruction ambiguity. Ed25519 has no algorithm parameter (the `null` digest arg).
 */

export interface KeyPair {
  kid: string;
  /** base64(DER SPKI) public key */
  publicKey: string;
  /** base64(DER PKCS8) private key — keep secret, never put in a receipt or repo */
  privateKey: string;
}

/**
 * The 8 canonical small-order Ed25519 public-key encodings (the torsion subgroup of order dividing 8:
 * identity, the order-2 point, the two order-4 points, the four order-8 points), as 32-byte
 * little-endian point encodings. CROSS-IMPL CONSENSUS: node:crypto/OpenSSL ACCEPTS a low-order
 * public key — a small-subgroup key passes createPublicKey + the curve-type pin + the canonical-SPKI
 * round-trip — whereas the independent Python reference decodes the point and can REJECT it. The SAME
 * signed bytes then split VALID(TS) / TAMPERED(PY), breaking the "two independent verifiers agree"
 * guarantee. We reject these encodings in BOTH impls so they agree. A
 * legitimate signing key is NEVER a low-order point (key generation samples a full-order point), so this
 * changes no valid behavior. (Mirrors libsodium's has_small_order / ZIP-215's small-order rejection;
 * the chosen convention is documented in THREAT-MODEL.md T15 + the spec verification section.)
 *
 * CORRECTION (2026-08-15). An earlier version of this comment gave the reason as "node:crypto/OpenSSL
 * verify is *cofactored*". That is FALSE, and it was load-bearing: it was cited into an IETF draft as
 * a measured nonconformance of this implementation and into a security task, and both had to be
 * withdrawn. Measured here — node v23.7.0 links OpenSSL 3.6.3, whose crypto/ec/curve25519.c says
 * verbatim "note that we have used the strict verification equation here … we checked that
 * ENC( [h](-A) + [s]B ) == r", and names the cofactored form "the less strict verification equation".
 * What this constant closes is a divergence in KEY VALIDATION — which points each library admits as a
 * public key — not in the verification equation; the two are different questions. And the equation
 * OpenSSL executes is a property of the LINKED VERSION, not of this package, so any future claim
 * about it must name the Node/OpenSSL pair it was measured on rather than asserting it in the
 * abstract. The conclusion above was always right; only this reason for it was wrong.
 */
// ── BEGIN SHARED STRICT-ED25519 RULE ─────────────────────────────────────────────────────────────
// Generated byte-for-byte into packages/approval-artifacts/src/inert-core/ed25519-strict.ts by
// scripts/sync-inert-core.mjs; CI (`npm run check:inert-core`) fails when the copy drifts. Everything
// between the BEGIN and END lines uses only bufferFrom, bufToString, byteLength, mapGet, mapSet,
// mapSize, newMap, toBigInt (./intrinsics.js) and membership (./inert.js).
const isSmallOrderPubkey = membership([
  "0100000000000000000000000000000000000000000000000000000000000000", // order 1 (identity)
  "ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", // order 2
  "0000000000000000000000000000000000000000000000000000000000000000", // order 4
  "0000000000000000000000000000000000000000000000000000000000000080", // order 4
  "26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc05", // order 8
  "26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc85", // order 8
  "c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac037a", // order 8
  "c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac03fa", // order 8
]);

/** Field prime p = 2^255 - 19. */
const P25519 = (1n << 255n) - 19n;
/** Edwards curve constant d = -121665/121666 mod p (RFC 8032 §5.1). */
const D25519 = 37095705934669439343138083508754565189542113879843219016388785533085940283555n;
/** sqrt(-1) mod p = 2^((p-1)/4) mod p (RFC 8032 §5.1.3 step 3). */
const SQRT_M1_25519 = 19681161376707505956807079304988542015446066515923890162744021073123829784752n;
/** Prime group order L = 2^252 + 27742317777372353535851937790883648493 (RFC 8032 §5.1). */
const L25519 = (1n << 252n) + 27742317777372353535851937790883648493n;

/** Non-negative residue mod p. */
function fieldMod(a: bigint): bigint {
  const r = a % P25519;
  return r < 0n ? r + P25519 : r;
}

/** base^exp mod m by square-and-multiply. BigInt operators only — no bare global is called. */
function modPow(base: bigint, exp: bigint, m: bigint): bigint {
  let result = 1n;
  let b = base % m;
  let e = exp;
  while (e > 0n) {
    if ((e & 1n) === 1n) result = (result * b) % m;
    b = (b * b) % m;
    e >>= 1n;
  }
  return result;
}

/**
 * Strict RFC 8032 §5.1.3 decoding of a 32-byte point encoding. Returns the affine point as a
 * two-element array [x, y] (indexed, never destructured), or null when:
 *   1. the y coordinate (the low 255 bits) is not canonical (y >= p);
 *   2. y does not decode to a curve point (x^2 = (y^2 - 1) / (d*y^2 + 1) has no square root);
 *   3. x = 0 and the sign bit is set ("If x = 0, and x_0 = 1, decoding fails").
 * After these steps every accepted encoding is the one canonical encoding of its point.
 */
function decodeStrictEd25519Point(raw: Uint8Array): bigint[] | null {
  if (byteLength(raw) !== 32) return null;
  const xSign = (raw[31]! & 0x80) !== 0;
  const yBytes = bufferFrom(raw);
  yBytes[31] = yBytes[31]! & 0x7f;
  let y = 0n;
  // T18: `BigInt` is a bare global; building y through it would let `globalThis.BigInt = () => 0n`
  // collapse every point to y = 0. The captured `toBigInt` keeps this gate independent of the global.
  for (let i = 31; i >= 0; i--) y = (y << 8n) | toBigInt(yBytes[i]!);
  // 1. Canonical y. OpenSSL accepts a y >= p encoding AND re-exports it unchanged, so an SPKI
  //    round-trip cannot catch it.
  if (y >= P25519) return null;
  // 2. Recover x (RFC 8032 §5.1.3 steps 2-3).
  const y2 = (y * y) % P25519;
  const u = fieldMod(y2 - 1n);
  const v = (D25519 * y2 + 1n) % P25519;
  const v3 = (((v * v) % P25519) * v) % P25519;
  const v7 = (((v3 * v3) % P25519) * v) % P25519;
  let x = (((u * v3) % P25519) * modPow((u * v7) % P25519, (P25519 - 5n) / 8n, P25519)) % P25519;
  const vx2 = (v * ((x * x) % P25519)) % P25519;
  if (vx2 !== u) {
    if (vx2 !== fieldMod(-u)) return null;
    x = (x * SQRT_M1_25519) % P25519;
  }
  // 3. x = 0 with the sign bit set is not a valid encoding.
  if (x === 0n && xSign) return null;
  if (((x & 1n) === 1n) !== xSign) x = P25519 - x;
  return [x, y];
}

/** RFC 8032 §5.1.4 addition on extended coordinates [X, Y, Z, T]; complete, so also used to double. */
function extendedAdd(p: bigint[], q: bigint[]): bigint[] {
  const a = ((p[1]! - p[0]!) * (q[1]! - q[0]!)) % P25519;
  const b = ((p[1]! + p[0]!) * (q[1]! + q[0]!)) % P25519;
  const c = (((2n * p[3]!) % P25519) * ((q[3]! * D25519) % P25519)) % P25519;
  const d = (((2n * p[2]!) % P25519) * q[2]!) % P25519;
  const e = b - a;
  const f = d - c;
  const g = d + c;
  const h = b + a;
  return [(e * f) % P25519, (g * h) % P25519, (f * g) % P25519, (e * h) % P25519];
}

/** Remembered step-5 results by key hex; replaced wholesale once it reaches its bound. */
let primeOrderSubgroupCache = newMap<string, boolean>();

/** True when [L]P is the identity, i.e. P lies in the prime-order subgroup (no torsion component). */
function isInPrimeOrderSubgroup(point: bigint[]): boolean {
  const base = [point[0]!, point[1]!, 1n, (point[0]! * point[1]!) % P25519];
  let acc = [0n, 1n, 1n, 0n];
  for (let i = 252n; i >= 0n; i--) {
    acc = extendedAdd(acc, acc);
    if (((L25519 >> i) & 1n) === 1n) acc = extendedAdd(acc, base);
  }
  return fieldMod(acc[0]!) === 0n && fieldMod(acc[1]! - acc[2]!) === 0n;
}

/**
 * STRICT PUBLIC-KEY VALIDATION for a raw 32-byte Ed25519 public key: refuse non-canonical and
 * small-order key encodings (RFC 8032 §5.1.3 decoding + small-order rejection), and keys outside
 * the prime-order subgroup. Every verifier in this repository applies the same rule at key load:
 *   1-3. strict decoding (decodeStrictEd25519Point);
 *   4. the point MUST NOT be one of the 8 small-order points (after 1-3 each has one encoding);
 *   5. the point MUST lie in the prime-order subgroup ([L]A = identity), which refuses mixed-order
 *      keys (a prime-order point plus a small-order component).
 * A key produced by Ed25519 key generation passes every step.
 */
export function isStrictEd25519PublicKeyBytes(raw: Uint8Array): boolean {
  const point = decodeStrictEd25519Point(raw);
  if (point === null) return false;
  const hex = bufToString(bufferFrom(raw), "hex");
  if (isSmallOrderPubkey(hex)) return false;
  // Step 5 costs one 253-bit scalar multiplication; its result is a pure function of the key bytes,
  // so it is remembered per key (bounded, captured Map methods only).
  const known = mapGet(primeOrderSubgroupCache, hex);
  if (known !== undefined) return known;
  const result = isInPrimeOrderSubgroup(point);
  if (mapSize(primeOrderSubgroupCache) >= 4096) primeOrderSubgroupCache = newMap<string, boolean>();
  mapSet(primeOrderSubgroupCache, hex, result);
  return result;
}

/**
 * STRICT SIGNATURE-R VALIDATION: the R half of an Ed25519 signature must be canonically encoded
 * (decoding steps 1-3 above) and MUST NOT be one of the 8 small-order points. With a prime-order key
 * and the cofactorless equation [S]B = R + [k]A, no R outside the prime-order subgroup can verify.
 */
export function isStrictEd25519SignatureRBytes(raw: Uint8Array): boolean {
  if (decodeStrictEd25519Point(raw) === null) return false;
  return !isSmallOrderPubkey(bufToString(bufferFrom(raw), "hex"));
}
// ── END SHARED STRICT-ED25519 RULE ───────────────────────────────────────────────────────────────

/**
 * ── C-01 ROUTE 2, CLOSED AT THE SINK ──────────────────────────────────────────────────────────────
 * `Buffer.from` is a writable property of a mutable global. `c01_buffer.mjs` replaced it so that an
 * HONEST keyring entry's base64 string decoded to the ATTACKER's public-key bytes: the receipt then
 * verified VALID under the honest kid, with `signaturesVerified: true`, against a keyring the
 * attacker's key was never in. Bytes-in does not touch this — it is key DECODING, not input
 * traversal — so it closes here or not at all. Every `Buffer` operation below now goes through a
 * capture taken at module-evaluation time (`src/intrinsics.ts`), including `toString`, `equals` and
 * `subarray`, each of which is an equally writable prototype method reached from a value.
 */

export function generateKeyPair(kid: string): KeyPair {
  const { publicKey, privateKey } = generateEd25519KeyPair();
  // `keyExportSpkiDer` for the public key and captured `bufToString` for the base64 — producer side,
  // but the enumerator holds the whole TCB to one rule and there is no reason to keep a live lookup here.
  return {
    kid,
    publicKey: bufToString(keyExportSpkiDer(publicKey), "base64"),
    privateKey: bufToString(keyExportPkcs8Der(privateKey), "base64"),
  };
}

/** Sign a message (the receipt digest) with an Ed25519 private key. Returns base64. */
export function signEd25519(privateKeyB64: string, message: Buffer): string {
  const key = createPrivateKeyCaptured({
    key: bufferFrom(privateKeyB64, "base64"),
    format: "der",
    type: "pkcs8",
  });
  // Pin the curve: sign(null, …) dispatches on the KEY type, so an Ed448/EC/RSA key would
  // silently produce a non-Ed25519 signature under a receipt that declares sig.alg="ed25519".
  // `asymmetricKeyType` is read through the CAPTURED accessor — see the verify path for why.
  if (asymmetricKeyType(key) !== "ed25519") throw new Error("signEd25519: key is not an Ed25519 key");
  return bufToString(ed25519Sign(message, key), "base64");
}

/** Verify an Ed25519 signature. Never throws — malformed key/sig returns false. */
export function verifyEd25519(publicKeyB64: string, message: Buffer, signatureB64: string): boolean {
  try {
    const der = bufferFrom(publicKeyB64, "base64");
    // Canonical base64 for the keyring public key too: node's Buffer.from is lenient
    // (whitespace / URL-safe / missing padding), so a non-canonical key STRING would verify VALID in TS
    // while the strict Python reference rejects it — a consensus divergence on a logically-identical key.
    if (bufToString(der, "base64") !== publicKeyB64) return false;
    // R3-02: captured constructor — a `syncBuiltinESMExports()` poison that substituted an attacker
    // key object for the honest DER cannot reach this snapshot.
    const key = createPublicKeyCaptured({ key: der, format: "der", type: "spki" });
    // PIN THE CURVE. verify(null, …) dispatches the verification algorithm on the KEY's type,
    // NOT on a fixed Ed25519. Without this, an Ed448 (or any verify(null)-compatible) public key in
    // the keyring + a genuine signature under it verifies TRUE even though the receipt declares
    // sig.alg="ed25519" — algorithm/key confusion (CWE-347). The COSE path pins the curve-specific
    // Ed25519 alg-id (-19, RFC 9864) — unlike the generic EdDSA (-8) it does NOT admit Ed448 — but
    // this key-type pin remains the durable defense on BOTH verifyChain and COSE paths.
    // T18, one property-access over: `asymmetricKeyType` is an ACCESSOR on
    // `AsymmetricKeyObject.prototype` (measured — configurable, `get` is a function), NOT a data
    // property. `Object.defineProperty(proto, "asymmetricKeyType", { get: () => "ed25519" })` makes
    // this pin bless an Ed448 key holding a genuine Ed448 signature. Read through the captured getter.
    if (asymmetricKeyType(key) !== "ed25519") return false;
    // Reject NON-CANONICAL SPKI (e.g. valid key + trailing garbage): OpenSSL's DER parser
    // accepts trailing bytes, so one logical key could have many encodings. A trust layer must
    // treat a key's encoding as canonical, so any future key-bytes-based logic (fingerprints,
    // dedup, byte-pinning) cannot be bypassed by re-encoding. Re-export and require byte-equality.
    // R3-09: captured `export`. This round-trip (re-export the parsed key and byte-compare against the
    // input DER) is the ONLY check that rejects a noncanonical SPKI, because OpenSSL re-exports it to
    // canonical form. A live `key.export -> der` poison turned the compare into a tautology and let a
    // 45-byte noncanonical key through; the captured method restores the real re-encoding.
    const canonical = keyExportSpkiDer(key);
    if (!bufEquals(canonical, der)) return false;
    // CROSS-IMPL CONSENSUS on the PUBLIC KEY. Which encodings a library admits as a public key is a
    // property of the linked library version, so the key rule is enforced here, identically in all five
    // verifiers, and decided from the key bytes alone before the signature is read:
    // canonical y, RFC 8032 §5.1.3 decoding, no x = 0 with the sign bit, not small-order
    // (see isStrictEd25519PublicKeyBytes above).
    const raw = bufSubarray(canonical, 12); // 12-byte Ed25519 SPKI prefix -> trailing 32 raw key bytes
    if (!isStrictEd25519PublicKeyBytes(raw)) return false;
    // STRICT, CANONICAL base64 for the signature. sig.value is NOT covered by the receipt hash, so its
    // exact byte string is unconstrained by the chain — only the decoded 64 bytes matter cryptographically.
    // node's Buffer.from(…, "base64") is LENIENT (silently ignores embedded whitespace, missing '='
    // padding, and trailing garbage), so many distinct strings decode to ONE valid 64-byte signature →
    // sig.value is non-canonical, and a receipt this verifier accepts is rejected (TAMPERED) by the strict
    // Python reference (base64decode validate=True), breaking the cross-impl consensus bar.
    // Require exactly 64 bytes AND that the input round-trips to its own canonical base64 encoding.
    const sigBytes = bufferFrom(signatureB64, "base64");
    // `byteLength`, not `.length`: on a Buffer, `length` is a CONFIGURABLE ACCESSOR on
    // `%TypedArray%.prototype` (measured), so `sigBytes.length` is a poisonable read, not the own
    // data property a plain array has.
    if (byteLength(sigBytes) !== 64 || bufToString(sigBytes, "base64") !== signatureB64) return false;
    // R must be canonically encoded and not small-order (the same rule in all five verifiers).
    if (!isStrictEd25519SignatureRBytes(bufSubarray(sigBytes, 0, 32))) return false;
    // EXPLICIT S < L scalar check (RFC 8032 §5.1.7 / T14). sigBytes = R (32 bytes) || S (32 bytes,
    // little-endian). A malleated signature S' = S + L (for any valid (R, S)) verifies under the SAME
    // equation as the original (the group has order L, so S and S+L are congruent mod L) — S' is a
    // SECOND, non-canonical encoding of an already-valid signature (Ed25519 signature malleability).
    // node:crypto/OpenSSL already rejects S >= L at verification time as of this writing, but that is a
    // property of the underlying OpenSSL build's *runtime* behavior, not a property this reference
    // implementation asserts on its own. Checking S < L explicitly here makes rejection a documented,
    // implementation-owned invariant — independent of whatever a future Node/OpenSSL upgrade does —
    // and matches the independent Python reference, which performs the identical check (impl-py/noa_verify.py).
    const L = 2n ** 252n + 27742317777372353535851937790883648493n;
    let S = 0n;
    // Same captured `BigInt` as the y<q gate. (This gate alone does NOT flip under the poison —
    // OpenSSL rejects S >= L independently — which is exactly why it must not be reported as the
    // proof of T18; the y<q gate is where the poison actually buys an acceptance.)
    for (let i = 63; i >= 32; i--) S = (S << 8n) | toBigInt(sigBytes[i]!);
    if (S >= L) return false;
    // THE SIGNATURE VERDICT, through the load-time snapshot of `crypto.verify` (T17).
    return ed25519Verify(message, key, sigBytes);
  } catch {
    return false;
  }
}

/** A keyring maps a key id (`kid`) to its base64 SPKI public key. */
export type Keyring = Record<string, string>;

/**
 * Optional identity binding: `agent.id` -> the `kid`(s) authorized to sign for it. Supplied
 * out-of-band by the verifier (the SAME trust class as the keyring). When passed to `verifyChain`,
 * a receipt whose `(agent.id, sig.kid)` pairing is not listed here is rejected as `UNTRUSTED` — this
 * is what upgrades attribution from "a keyring-trusted key signed this" to "THIS agent.id signed this",
 * closing cross-agent impersonation in a multi-key keyring. When omitted, attribution stays kid-level
 * (the weaker, documented guarantee). The manifest itself is a trust-root the operator vouches for
 * (like the keyring); distributing it as a SIGNED statement is a deployment concern, not enforced here.
 */
export type IdentityManifest = Record<string, string[]>;
