/**
 * The `noa.chain-facts/0.1` MIRROR TEST — the committed JSON Schema is the normative shape, the
 * hand-rolled `validateChainFacts` is the enforced one (this package ships no schema evaluator and
 * gains no dependency for one), and this file is what keeps the two from drifting: FOR EVERY FIELD
 * the schema constrains, a mutation the schema refuses must be refused by the validator too.
 *
 * The violations are DERIVED FROM THE SCHEMA FILE, not hand-listed per field: required-member
 * deletion, unknown-member injection, pattern violation, enum violation, type violation and
 * integer-minimum violation are generated by walking the schema's own properties. A field added to
 * the schema tomorrow fails this test until the validator learns it — in either direction.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { validateChainFacts, CHAIN_FACTS_SPEC } from "../src/index.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const schema = JSON.parse(readFileSync(join(__dirname, "..", "schema", "noa-chain-facts-0.1.schema.json"), "utf8"));

const VALID = {
  spec: "noa.chain-facts/0.1",
  network: "eip155:8453",
  asset: "eip155:8453/erc20:0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
  authorizationState: true,
  authorizationUsedLogs: [
    { txHash: "0x" + "3f".repeat(32), blockNumber: 1, logIndex: 0, blockTimestamp: "2026-08-13T10:05:04.000Z", txStatus: "SUCCESS",
      nonce: "0x" + "9c".repeat(32), authorizer: "0x1111111111111111111111111111111111111111" },
  ],
  authorizationCanceledLogs: [
    { txHash: "0x" + "4a".repeat(32), blockNumber: 2, logIndex: 1, blockTimestamp: "2026-08-13T10:05:04Z", txStatus: "SUCCESS",
      nonce: "0x" + "9c".repeat(32), authorizer: "0x1111111111111111111111111111111111111111" },
  ],
  transfer: {
    source: "TRANSFER_LOG",
    address: "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
    logIndex: 2,
    from: "0x1111111111111111111111111111111111111111",
    to: "0x2222222222222222222222222222222222222222",
    value: "1000000",
    txHash: "0x" + "3f".repeat(32),
    blockNumber: 1,
  },
  headBlockNumber: 100,
  queriedAt: "2026-08-13T10:06:30.000Z",
};

const clone = () => JSON.parse(JSON.stringify(VALID));

test("the valid record is accepted (anti-vacuity control for every refusal below)", () => {
  assert.deepEqual(validateChainFacts(VALID), { ok: true });
  assert.equal(VALID.spec, CHAIN_FACTS_SPEC);
});

test("transfer: null is accepted (the schema's oneOf null branch)", () => {
  const v = clone();
  v.transfer = null;
  assert.deepEqual(validateChainFacts(v), { ok: true });
});

/** A value that violates the given schema property node, derived from the node itself. */
function violationFor(node) {
  if (node.const !== undefined) return "not-the-const";
  if (node.enum !== undefined) return "NOT_AN_ENUM_MEMBER";
  if (node.pattern !== undefined) return "definitely does not match";
  if (node.$ref !== undefined) return "not-a-timestamp"; // both $refs here resolve to string grammars
  if (node.type === "boolean") return "true"; // string, not boolean
  if (node.type === "integer") return -1; // below every minimum in this schema
  if (node.type === "array") return {}; // object, not array
  return Symbol("unconstrained"); // would indicate a schema field this test does not understand
}

test("schema mirror: every ROOT field — missing required, unknown member, per-field violation", () => {
  // required-member deletion
  for (const k of schema.required) {
    const v = clone();
    delete v[k];
    assert.equal(validateChainFacts(v).ok, false, `schema requires "${k}"; validator accepted its absence`);
  }
  // additionalProperties: false
  const extra = clone();
  extra.smuggled = 1;
  assert.equal(validateChainFacts(extra).ok, false, "schema refuses unknown root members; validator accepted one");
  // per-field constraint violation
  for (const [k, node] of Object.entries(schema.properties)) {
    if (k === "transfer" || k === "authorizationUsedLogs" || k === "authorizationCanceledLogs") continue; // structured below
    const v = clone();
    v[k] = violationFor(node);
    assert.equal(typeof v[k] === "symbol" ? false : validateChainFacts(v).ok, false,
      `schema constrains "${k}"; validator accepted a violating value`);
  }
});

test("schema mirror: authorizationUsedLogs entries — every log field", () => {
  const logSchema = schema.properties.authorizationUsedLogs.items;
  for (const k of logSchema.required) {
    const v = clone();
    delete v.authorizationUsedLogs[0][k];
    assert.equal(validateChainFacts(v).ok, false, `log schema requires "${k}"`);
  }
  const extra = clone();
  extra.authorizationUsedLogs[0].smuggled = 1;
  assert.equal(validateChainFacts(extra).ok, false, "log schema refuses unknown members");
  for (const [k, node] of Object.entries(logSchema.properties)) {
    const v = clone();
    v.authorizationUsedLogs[0][k] = violationFor(node);
    assert.equal(validateChainFacts(v).ok, false, `log schema constrains "${k}"`);
  }
  const notArray = clone();
  notArray.authorizationUsedLogs = {};
  assert.equal(validateChainFacts(notArray).ok, false, "authorizationUsedLogs must be an array");
});

test("schema mirror: authorizationCanceledLogs entries — same shape via $defs.canceledLog", () => {
  const logSchema = schema.$defs.canceledLog;
  for (const k of logSchema.required) {
    const v = clone();
    delete v.authorizationCanceledLogs[0][k];
    assert.equal(validateChainFacts(v).ok, false, `canceledLog schema requires "${k}"`);
  }
  const extra = clone();
  extra.authorizationCanceledLogs[0].smuggled = 1;
  assert.equal(validateChainFacts(extra).ok, false, "canceledLog schema refuses unknown members");
  for (const [k, node] of Object.entries(logSchema.properties)) {
    const v = clone();
    v.authorizationCanceledLogs[0][k] = violationFor(node);
    assert.equal(validateChainFacts(v).ok, false, `canceledLog schema constrains "${k}"`);
  }
});

test("schema mirror: transfer — every member, plus the not-an-object refusal (R-19(b) uniqueness at the record boundary)", () => {
  const transferSchema = schema.properties.transfer.oneOf.find((b) => b.type === "object");
  for (const k of transferSchema.required) {
    const v = clone();
    delete v.transfer[k];
    assert.equal(validateChainFacts(v).ok, false, `transfer schema requires "${k}"`);
  }
  const extra = clone();
  extra.transfer.smuggled = 1;
  assert.equal(validateChainFacts(extra).ok, false, "transfer schema refuses unknown members");
  for (const [k, node] of Object.entries(transferSchema.properties)) {
    const v = clone();
    v.transfer[k] = violationFor(node);
    assert.equal(validateChainFacts(v).ok, false, `transfer schema constrains "${k}"`);
  }
  // The oneOf admits null | ONE object. An array of transfers matches neither branch — and that IS
  // the uniqueness rule at the record boundary: a caller with two qualifying logs cannot produce a
  // conforming record, and presenting both is refused, never reduced to a pick.
  const twoTransfers = clone();
  twoTransfers.transfer = [clone().transfer, clone().transfer];
  assert.equal(validateChainFacts(twoTransfers).ok, false, "an array of transfers must be refused, never picked from");
});

test("uppercase hex is refused everywhere the schema pins lowercase (EIP-55 casing is presentation, not identity)", () => {
  for (const mutate of [
    (v) => { v.asset = v.asset.toUpperCase(); },
    (v) => { v.network = "EIP155:8453"; },
    (v) => { v.authorizationUsedLogs[0].txHash = v.authorizationUsedLogs[0].txHash.toUpperCase(); },
    (v) => { v.transfer.address = v.transfer.address.toUpperCase(); },
    (v) => { v.transfer.from = v.transfer.from.toUpperCase(); },
    (v) => { v.transfer.to = v.transfer.to.toUpperCase(); },
  ]) {
    const v = clone();
    mutate(v);
    assert.equal(validateChainFacts(v).ok, false, "uppercase variant accepted");
  }
});
